### ISSUE TITLE
Proposal: Rename http.responseCodes metrics

### ISSUE THREAD

**Issue by aditya-konarde** [jenkinsci/prometheus-plugin#100]
Hello, 

We currently have the Jenkins UI response code metrics named as follows: 
`http_responseCodes_<responseType>_total`

I would suggest the following convention to keep it consistent with the other metrics, and make it easier to discover: 
- Prefix metric name with `jenkins_`
- Add response code in metric label instead of in metric name. The response codes have a limited cardinality thus should not be a problem

After the suggested rename, the metrics will look like: 

`jenkins_http_response_total`

And then if you'd like to filter by code
`jenkins_http_response_total{code="404"}`

**Comment by aditya-konarde** [comment]
@lsjostro @markyjackson-taulia please take a look. I am happy to provide additional context/details if needed.

**Comment by aditya-konarde** [comment]
Additional context, this change makes it MUCH easier if you want to alert on % error rate across responses. For example you'd be able to do: 

High 5xx Error Rate
```
sum(rate(jenkins_http_response_total{job="jenkins",code=~"^(?:5..)$"}[5m]))
/
sum(rate(jenkins_http_response_total{job="jenkins"}[5m])) * 100 > 1
```

**Comment by darxriggs** [comment]
Please also keep best practices in mind and have a look how others expose such common HTTP metrics.
- https://prometheus.io/docs/practices/naming/
- https://prometheus.io/docs/practices/instrumentation/#use-labels

**Comment by aditya-konarde** [comment]
Thanks for the suggestions @darxriggs ; 

@markyjackson-taulia wdyt about this? I see the for-review label. Have you had a chance to take a closer look at the proposal?

**Comment by aditya-konarde** [comment]
@markyjackson-taulia why was this issue closed? Has this been fixed in a later release that I missed?

**Comment by markyjackson-taulia** [comment]
This was not added as I feel how we are using the current response code metric are in line with the prometheus best practices as noted here:
https://prometheus.io/docs/practices/naming/
https://prometheus.io/docs/practices/instrumentation/#use-labels

Now if you think there is a more to do I encourage either a pr or we can somehow collaborate in your proposal
