### ISSUE TITLE
Documentation: Provide alerting rule examples

### ISSUE THREAD

**Issue by aditya-konarde** [jenkinsci/prometheus-plugin#101]
As a consumer for this project, I now have metrics about Jenkins in my Prometheus instance. 

What's next is I'd like to alert on known failure scenarios. Currently, I have to hand-craft a bunch of alerting rules.

Proposal: 
- Document common alerts in the repo, so that anyone getting started with the plugin doesn't need to reinvent them

**Comment by aditya-konarde** [comment]
I'm happy to work on this once I have a reasonable set of alerts which I'm currently working on.

**Comment by markyjackson-taulia** [comment]
Closing in favor of #113 which I have added this request in to
