### ISSUE TITLE
Release wanted :-)

### ISSUE THREAD

**Issue by jwoehrle** [jenkinsci/prometheus-plugin#102]
Hi there,

I was wondering if there is a release somewhere which contains the changes made here:

https://github.com/jenkinsci/prometheus-plugin/blob/master/src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java#L79

The latest release on https://plugins.jenkins.io/prometheus is 2.0.0 which unfortunately does not contain the changes made on the JobCollector 5 months back unfortunately.

Do you have any plans on releasing a new version with those changes?

Thanks and regards

Jörg

**Comment by markyjackson-taulia** [comment]
I am working hard to get a new release out. I am also looking for co-maintainers to help with the load as I am the only one
