### ISSUE TITLE
PROMETHEUS_NAMESPACE is not honoured

### ISSUE THREAD

**Issue by hairesis** [jenkinsci/prometheus-plugin#104]
According to https://prometheus.io/docs/practices/naming/ 
> A metric name should have a (single-word) application prefix relevant to the domain the metric belongs to. The prefix is sometimes referred to as namespace by client libraries. 

### Steps to reproduce
Setup the PROMETHEUS_NAMESPACE parameter
![image](https://user-images.githubusercontent.com/84026/57690585-e0e79e80-7639-11e9-9ed8-daa7d9581813.png)

### Expected behaviour
Metrics are prefixed with myapi or default

### Actual behaviour
No prefix
![image](https://user-images.githubusercontent.com/84026/57690645-02488a80-763a-11e9-8dab-012e10cc284b.png)

### Server configuration

**Operating system**:
Centos 7

**Jenkins Version**:
Jenkins ver. 2.164.2

**Plugin Version**:
2.0.0

**Comment by markyjackson-taulia** [comment]
@hairesis I will try to reproduce this over the next few days. Can you provide me what your prometheus scrape config (prometheus.yaml) looks like (minus any secret stuff)?

**Comment by markyjackson-taulia** [comment]
I was unable to reproduce this in the new version
