### ISSUE TITLE
Release 2.0.4 missing from plugins.jenkins.io

### ISSUE THREAD

**Issue by jamesrobson-pio** [jenkinsci/prometheus-plugin#112]
The plug-in page lists version 2.0.4, but it is not present in the list of binaries at https://updates.jenkins.io/download/plugins/prometheus/

**Comment by markyjackson-taulia** [comment]
Something is wrong and I will get it figured out today

**Comment by shamil** [comment]
We are still stuck on version `2.0.0` :(

**Comment by markyjackson-taulia** [comment]
Please use [Release 2.0.6](https://github.com/jenkinsci/prometheus-plugin/releases/tag/prometheus-2.0.6) which is now present in the upgrade center after much fixing on the Jenkins Infra side. I am also now a member of the infra team ;-)
