### ISSUE TITLE
Run book Style Documentation

### ISSUE THREAD

**Issue by markyjackson-taulia** [jenkinsci/prometheus-plugin#113]
A task for me to better document the setup of the plugin

**Comment by markyjackson-taulia** [comment]
Also tracking here: https://issues.jenkins-ci.org/browse/JENKINS-58271

**Comment by markyjackson-taulia** [comment]
As a consumer for this project, I now have metrics about Jenkins in my Prometheus instance.

What's next is I'd like to alert on known failure scenarios. Currently, I have to hand-craft a bunch of alerting rules.

Proposal:

Document common alerts in the repo, so that anyone getting started with the plugin doesn't need to reinvent them

**Comment by waveywaves** [comment]
@markyjackson-taulia I would be working on this

**Comment by markyjackson-taulia** [comment]
@waveywaves Did you want to continue on this?

**Comment by markyjackson-taulia** [comment]
Closing this out.
