### ISSUE TITLE
Add configuration option to 'Enable/Disable' jobs stages and steps metrics collection

### ISSUE THREAD

**Issue by sainouche** [jenkinsci/prometheus-plugin#116]
Hi,

We have deployed 'prometheus-plugin' on production and we are facing on our bigger Jenkins instance the issue #82. Waiting for the fix, an interesting configuration option could be 'Enable/Disable' of the job's stages and steps metrics collection. 

### Expected behavior
Add the following option to `prometheus-plugin`:

- [ ]   Enable stages steps metrics

Please, find below, the source code sample, waiting for the PR if interested:

- Class **JobCollector**
- Line : **276**
`
if (!ignoreBuildStepsMetrics) {
    logger.debug("getting the sorted stage nodes for run[{}] from job [{}]", run.getNumber(), job.getName());
    List<FlowNode> stages = getSortedStageNodes(workflowRun.getExecution());
    for (FlowNode stage : stages) {
        observeStage(job, run, stage);
   }
}
`

### Server configuration

**Operating system**:
RHEL 7 / Ubuntu 14.04
**Jenkins Version**:
Jenkins ver. 2.164.3
**Plugin Version**:

Thanks,

### Notify

@markyjackson-taulia

**Comment by sainouche** [comment]
@markyjackson-taulia thanks for the acknowledge.
FYI, on our side and on production, we are managing thousands of multibranch jobs and facing #82 on two of our Production Jenkins instances. So, obliged to fix on our side, but really want to keep standard and use your official plugin.
Please, let me know if this feature is interesting for you.
Thanks,

**Comment by markyjackson-taulia** [comment]
This should no longer be happening. I am prepping a release currently
