### ISSUE TITLE
Getting same value for almost 131 metrics

### ISSUE THREAD

**Issue by Vatsaldhar26** [jenkinsci/prometheus-plugin#117]
There are in total 131 metrics, whose value are the same. 
Below are randomly picked few metrics, which i don't think have any relation with each other still they show same value, similarly there are 125 more with same value.

jenkins_queue_stuck_history_count 16643.0
vm_cpu_load_x100_window_5m_count 16643.0
jenkins_executor_count_history_count 16643.0
vm_memory_pools_Code_Cache_usage_x100_window_15m_count 16643.0
vm_memory_total_used_window_1h_count 16643.0
jenkins_node_offline_history_count 16643.0

**Comment by markyjackson-taulia** [comment]
@Vatsaldhar26 Can you let me know the plugin version, Jenkins version, and what your prometheus scrape config looks like (in your prometheus.yaml)?
Thanks

**Comment by Vatsaldhar26** [comment]
Prometheus metrics plugin : 2.0.0 
Jenkins Version : 2.155

Scrape config, Prometheus :  
 - job_name: 'jenkins'
    metrics_path: '/prometheus/'
    scheme: https
    static_configs:
      - targets: ['<jenkins_host_url>']

Also, I saw that it can use bearer token, but didn't find a way to get that in Jenkins, can you guide me for that also.

**Comment by markyjackson-taulia** [comment]
I see your missing the 2nd scrape config
