### ISSUE TITLE
How to get last build result from multiple jenkins instances?

### ISSUE THREAD

**Issue by Davis8988** [jenkinsci/prometheus-plugin#118]
I installed this plugin on a few Jenkins instances and configured 1 single Prometheus server to scrape all the Jenkins instances (a single scraping job for each Jenkins instance). But when I can only get the default_jenkins job's last build results. Meaning only 1 instance.  Is there a way to get last jobs build results of more than 1 Jenkins instance? Instead of the default_jenkins alone?

**Comment by markyjackson-taulia** [comment]
@Davis8988 That is currently not possible. You would need to configure multiple scrape configs

**Comment by Davis8988** [comment]
I see. Thanks.
You plugin is awsome by the way
