### ISSUE TITLE
No metrics for pipelines

### ISSUE THREAD

**Issue by BZaldua** [jenkinsci/prometheus-plugin#119]
I'm having some issues with the plugin. I can see the output of Jenkins metrics but when it comes to the execution of a pipeline I don't see any metrics related to builds or pipeline stages.

When I do a simple echo "Hello" job I do see this metrics but when it's changed to a pipeline I can see the total time but no each stage time.

Is there any configuration I'm missing in the pipeline or is a code issue?

**Comment by markyjackson-taulia** [comment]
@BZaldua can you share you pipeline config?

**Comment by BZaldua** [comment]
It's a declarative Jenkins pipeline, there's no much of a configuration. Just to trigger it when there's a commit to a certain repo. Regarding metrics, no configuration has been added

**Comment by markyjackson-taulia** [comment]
@BZaldua this dopest;t sound like a plugin problem as much as it sounds like a declarative pipeline problem. Also without having much in terms of configuration on your side I am not sure how I can help you. 
I can say that I have tested the plugin in a variety of ways including declarative and it works but again without knowing what you are doing on your end it is sort of hard to help

**Comment by BZaldua** [comment]
This is the pipeline I have:

```
pipeline {
    agent none

    options{
        gitLabConnection('Gitlab')
    }

    environment {
        PIPELINE_WORKSPACE = "workspace/${env.JOB_NAME} --- build ${env.BUILD_NUMBER}"
        PIPELINE_BRANCH_CODE = "${!env.gitlabBranch ? params.Branch : env.gitlabBranch}"
    }

    triggers {
        gitlab(
            triggerOnPush: true,
            triggerOnMergeRequest: false, 
            triggerOnNoteRequest: false,
            skipWorkInProgressMergeRequest: true,
            ciSkip: true,
            setBuildDescription: false,
            addNoteOnMergeRequest: false,
            addCiMessage: true,
            addVoteOnMergeRequest: false,
            acceptMergeRequestOnSuccess: false,
            branchFilterType: "RegexBasedFilter",
            sourceBranchRegex: "develop|release.*|hotfix.*",
            targetBranchRegex: "develop|release.*|hotfix.*",
            cancelPendingBuildsOnUpdate: false
        )
    }

    stages{
        stage('setup'){
            agent {
                node {
                    label 'master'
                    customWorkspace "${env.PIPELINE_WORKSPACE}"
                }
            }
            options {
                gitlabCommitStatus(name: 'Jenkins - build')
                lock(resource: "$env.JOB_NAME-build", inversePrecedence: true)
            }

            stages{
                stage('clone'){
                    // clone git repo
                }

                stage('build'){
                   sh label: 'build', script: ''' mvn clean package'''
                }
            }
        }
    }
}
```

What I would like is getting the metrics for the stages 'clone' and 'build' and what I'm getting is the total millisenconds of the whole pipeline execution. I installed the plugin in Jenkins and did nothing else because I saw some metrics already. I don't know what is missing or if the plugin is capable of doing what I want...

Thank you in advance!

**Comment by BZaldua** [comment]
Nevermind, I the solutions. Updating the plugin to 2.0.6 fixed it and now I get this metrics.

Thanks anyway!
