### ISSUE TITLE
jenkins_builds_duration_milliseconds_summary wont get displayed in prometheus

### ISSUE THREAD

**Issue by phhutter** [jenkinsci/prometheus-plugin#12]
add following environment vars:
```
PROMETHEUS_NAMESPACE=testing
PROMETHEUS_ENDPOINT=metrics
```

when i check my metrics

http://localhost:8080/metrics/
```
# HELP testing_jenkins_builds_duration_milliseconds_summary Summary of Jenkins build times in milliseconds by Job
# TYPE testing_jenkins_builds_duration_milliseconds_summary summary
testing_jenkins_builds_duration_milliseconds_summary_count{job="TEST1",} 1.0
testing_jenkins_builds_duration_milliseconds_summary_sum{job="TEST1",} 1.0
testing_jenkins_builds_duration_milliseconds_summary_count{job="TEST2",} 31.0
testing_jenkins_builds_duration_milliseconds_summary_sum{job="TEST2",} 31.0
```

But i cant see these entries in prometheus...
All the other metrics are working fine and get displayed.

**Comment by bernhardcygan** [comment]
Similar, but probably not identical: I can't see the build metrics starting with 'default_jenkins_builds' in Grafana, although I can see them when directly calling the exporter endpoint. Is this by intention ? How do I get these values into Grafana ? I was hoping to use something like ...count / ...sum for the average build time of a particular job.

**Comment by LzaldivarGS** [comment]
Same, every metric about builds isn't getting imported.

**Comment by Leviter** [comment]
When enabling debug logging on Jenkins, I get the following output:

`Collecting metrics for prometheus
Feb 26, 2018 9:18:53 AM FINE org.jenkinsci.plugins.prometheus.JobCollector collect
getting summary of build times in milliseconds by Job
Feb 26, 2018 9:18:53 AM FINE org.jenkinsci.plugins.prometheus.JobCollector collect
getting summary of build times by Job and Stage
Feb 26, 2018 9:18:54 AM FINE org.jenkinsci.plugins.prometheus.JobCollector collect
Collecting metrics for prometheus
Feb 26, 2018 9:18:54 AM FINE org.jenkinsci.plugins.prometheus.JobCollector collect
getting summary of build times in milliseconds by Job
Feb 26, 2018 9:18:54 AM FINE org.jenkinsci.plugins.prometheus.JobCollector collect
getting summary of build times by Job and Stage`

**Comment by hawky-4s-** [comment]
I experienced the same problem. 
My solution was set ACL in Jenkins to allow anonymous user to read jobs as that is the user prometheus scrape client is using.

**Comment by Leviter** [comment]
Thank you! This helped (at least) me in getting data into Prometheus.

**Comment by Leviter** [comment]
Now that I got it working, let me share what I did and also describe the situation we have...

We are using the Multi-branch plugin and have a private organisation on Github. So our repos are private. We can use our (personal) Github account to log into Jenkins. The prometheus plugin was not able to show the build metrics for those repos. Since we have also have a 'generic' user that is allowed to access Github and clone repos in order to be able to build them, I used the same user to create a token which I then use to do the authentication for the plugin for.

In the prometheus.yml (where we do the scraping of the metrics) I added a basic_authentication part where the username is the username of the 'generic' user. The password is the token that was generated on Github.

After this, it worked for me!

**Comment by Fredrik-Petersson** [comment]
As @hawky-4s- mentioned the metrics works when enabeling the "Allow anonymous read access" setting. For me this was not obvious where to find so this is the full instruction on how to set this;
1. In Jenkins GUI go to "Manage Jenkins"
2. Go to "Configure Global Security"
3. Under the "Authorization" section enable the "Allow anonymous read access" (sub setting of "Logged-in users can do anything"
4. Save and it will work without delay

Maybe this can be done in a safer way but for our test environments this is enough.

While at it it is nice to change the settings of the Prometheus Plugin to use "metrics" as default url (like localhost:8080/metrics/) and replace the "Default Namespace" with something more suitable:
1. Go to "Manage Jenkins"
2. Go to "Configure system"
3. Under "Prometheus" section change the "Path" value from "Prometheus" to "metrics"
4. Under the same section change the "Default Namespace" to what suits your needs. Leaving it blanks just names the metrices with "jenkins_" like the rest of the metrices.

**Comment by yogeshprasad** [comment]
To get the Job-related metrics for anonymous user enable the authentication setting inn the global setting 
![image](https://user-images.githubusercontent.com/7803152/47032648-81eba500-d190-11e8-9fb1-34553e92d5e4.png)

**Comment by markyjackson-taulia** [comment]
Closing this as you can enable the authentication setting in the global security setting

**Comment by madhurinalluri** [comment]
I changed the path to "metrics" I still got an error.
HTTP ERROR 404
Problem accessing /metrics/. Reason:

    Not Found
Can anyone help with this?

**Comment by 625440531** [comment]
@madhurinalluri 
1. Go to "Manage Jenkins"
2. Go to "Configure system"
3. find "Prometheus" section
4. config the "Path" as you want

the path "${jenkins_url}/metrics/currentUser/metrics?pretty=true" used by plugin metrics for  [metrics-plugin](https://github.com/jenkinsci/metrics-plugin) . so there has some conflict.

- Prometheus metrics plugin : 2.0.6
- Metrics Plugin ：4.0.2.6
- Jenkins ：  2.190.1
