### ISSUE TITLE
Support for configuring custom labels for the metrics collected from jenkins.

### ISSUE THREAD

**Issue by raghavendrapj** [jenkinsci/prometheus-plugin#125]
This is a feature request, Is it feasible to provide a way to configure custom labels as key value pairs to the metrics collected from jenkins. Most of the prometheus exporters will have such a requirement and helps us to group metrics based on those custom labels.

### Notify

@markyjackson-taulia

**Comment by redfive** [comment]
This would be excellent! I'm running 70+ Jenkins masters in docker containers and the ip:port set in the instance label isn't a useful designation for me to know which instance is doing what. The ability to override instance, or add a custom label would be extremely helpful

**Comment by redfive** [comment]
Any estimate on when a fix for this might be coming? Also, I'm happy to post a patch if I can just get a little guidance for where to hook this in.

**Comment by raghavendrapj** [comment]
Any updates on this one?

**Comment by markyjackson-taulia** [comment]
Adding this to the FY21 Q2 roadmap
