### ISSUE TITLE
Latest 2.0.6 leads to Single Sign On Nullpointer Exception and Pipeline configuration data goes missing

### ISSUE THREAD

**Issue by advorsky73** [jenkinsci/prometheus-plugin#126]
https://issues.jenkins-ci.org/browse/JENKINS-58940 
This issue documents the behavior change when 2.0.6 is installed.
Going back to 2.0.0 resolves the issue.

Additionally when "configuring" a pipeline job the SCM info went missing when 2.0.6 is active.
Without modifying the job this resolves when rolling back to 2.0.0.

As well the Pipeline Library SCM information in the system configuration went missing when 2.0.6 is active.
The worst part about this is that when you change another setting, you will save the Library config as well and loose all your pipeline library SCM information from your configuration.
Going back to 2.0.0 resolves this issue.

Jenkins Version: Latest LTS.

**Comment by sharkannon** [comment]
Jenkins LTS 2.176.3 (and .2) all latest plugins, having the Pipeline Job SCM missing as well from 2.0.0 -> 2.0.6.  If you view the data on disk, all the configurations are there they just aren't in the UI.. but once you hit "save" you lose basically everything.

**Comment by Snapstromegon** [comment]
I can reproduce this on LTS 2.204.2 with plugin version 2.0.7 (from github release page)

**Comment by markyjackson-taulia** [comment]
Please use the latest update via the update center
