### ISSUE TITLE
Add explicit CONTRIBUTING guidelines to the plugin

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/prometheus-plugin#129]
Right now there is no contributing guidelines in the repository. It would be great to have some.

**Comment by Sweta271097** [comment]
@oleg-nenashev Can I take up this issue?

**Comment by markyjackson-taulia** [comment]
@Sweta271097 That would be awesome!

**Comment by Sweta271097** [comment]
@markyjackson-taulia I'm on it. :)
