### ISSUE TITLE
Pipeline stage last build SUCCESS/FAILED

### ISSUE THREAD

**Issue by pdev1989** [jenkinsci/prometheus-plugin#138]
### Steps to reproduce
How can we reproduce the issue
1. Install prometheus-plugin v2.0.6 in the Jenkins
2. hit <your_jenkins>/prometheus

### Expected behaviour
I can't find a metric that shows `status of last build (succes/failed)` for **individual stages** in a pipeline

### Actual behaviour
I see only the metrics that count the number of builds of each stage in the pipeline. But, not the metrics that really shows what happned to the last build of a particular stage. It would be great to have this metric so I can build a nice dashboard that shows the status of last build of each individual stages in my pipeline. 

Best Regards. 

Notify
@markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
This is not currently a feature
