### ISSUE TITLE
Is it time for a new release?

### ISSUE THREAD

**Issue by chrisvanbreeden** [jenkinsci/prometheus-plugin#139]
Hi,

Is saw that my long waiting feature request was merged into master (diskspace usage) and I was wondering when it is going to be released...

We really need this at the company I am working at and we are no allowed to make/deploy our own plugin 'snapshot' versions.

Best regards,
Chris

@markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
MY goodness yes it is. I am doing 2 things.
- [] Prepare a 2020 roadmap
- [] Prepare a release the 1st week of Jan 2020

Why wait till Jan? Well to be honest it is the holidays coming up and work has me super busy with yearend items.

I will also be making the documentation better during the 1st week of Jan..
Hopefully this is understandable and thanks for the issue. I will leave this issue open as well.

**Comment by cpitstick-argo** [comment]
If you're going to do a new release, please make sure that https://github.com/jenkinsci/prometheus-plugin/pull/142 and https://github.com/jenkinsci/prometheus-plugin/pull/143 are included in it.

**Comment by markyjackson-taulia** [comment]
Closing this as I am preparing a new release with #142 and #143 in it
