### ISSUE TITLE
Build duration only when success

### ISSUE THREAD

**Issue by yutongz** [jenkinsci/prometheus-plugin#14]
Hi, I noticed currently, the build duration counts every build, but sometimes, we only cares these job built successfully. Do you think you can add a small check to filter these out?

**Comment by bernhardcygan** [comment]
Please check my fork at https://github.com/bernhardcygan/prometheus-plugin. If it works for you as well as for me, I will make a pull request.

**Comment by lsjostro** [comment]
Welcome to open a PR!
