### ISSUE TITLE
Do the job metrics need to be multi-threaded?

### ISSUE THREAD

**Issue by cpitstick-argo** [jenkinsci/prometheus-plugin#144]
While testing the Jenkins Prometheus plugin, we've noticed that even after [this performance fix](https://github.com/jenkinsci/prometheus-plugin/commit/db157bd7df5fe55fb057f36975678322c531afcf), it still seemed that Jenkins would hang sometimes for about a minute.

While I know that the plugin is supposed to [run asynchronously](https://github.com/jenkinsci/prometheus-plugin/commit/a1a5614a77394e66a829da53d4d326c4ef83ea55), our anecdotal testing indicates that something in the plugin is still locking up the main Jenkins thread.

So two thoughts:
1. Does anyone know what that might be? My guess is that within the PrometheusAsyncWorker something downstream is acquiring a lock, but what could that be?

2. In the meantime while we try to figure that out, one hypothesis is that the code [here](https://github.com/jenkinsci/prometheus-plugin/blob/master/src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java#L252) needs to be multi-threaded as the loop may be taking too long.

I'm thinking about implementing 2 and testing it, unless anyone in has any objections or thoughts as to what else might be going on here?

**Operating system**: Ubuntu

**Jenkins Version**:  2.204.1

**Plugin Version**: 2.0.7-snapshot

### Notify

@markyjackson-taulia
@lsjostro
@wojciechzachwieja

**Comment by markyjackson-taulia** [comment]
@cpitstick-argo A few others have had these issues and I started debugging and think I have the issue figured out and it is PrometheusAsyncWorker. I am working on a fix
