### ISSUE TITLE
Jenkins User Stats and Job Stats

### ISSUE THREAD

**Issue by monil536** [jenkinsci/prometheus-plugin#145]
Hi

Below are some question i had when i was recent working with prometheus. 

1. Is there a way to get a metric of total number of Users added via RBAC plugin ?
2. Is there a way to get a metric of total number of jenkins job with each type (Ex. free style,  multibranch, etc. ) ?
3. Is there a way to get metric of count of available plugin updates ?  

If this is some thing that is not available today than can we request this as a new feature ?. This stats will definitely help us to extend an overview of jenkins instance management.  

Thanks,
Monil

**Comment by markyjackson-taulia** [comment]
> Hi
> 
> Below are some question i had when i was recent working with prometheus.
> 
> 1. Is there a way to get a metric of total number of Users added via RBAC plugin ?
> 2. Is there a way to get a metric of total number of jenkins job with each type (Ex. free style,  multibranch, etc. ) ?
> 3. Is there a way to get metric of count of available plugin updates ?
> 
> If this is some thing that is not available today than can we request this as a new feature ?. This stats will definitely help us to extend an overview of jenkins instance management.
> 
> Thanks,
> Monil

1) Not yet but I have that on my roadmap
2) Not yet but I have that on my roadmap
3) Not yet but I have that on my roadmap
