### ISSUE TITLE
Add actual pipeline stage and run duration information for each run

### ISSUE THREAD

**Issue by perostman** [jenkinsci/prometheus-plugin#150]
### Steps to reproduce
How can we reproduce the issue
1. Inspect the metrics available for a pipeline job

### Expected behaviour
It would be very useful to have duration information published for every pipeline run for both the entire pipeline as well as each stage

### Actual behaviour
Currently, it seems like the only stage duration information is default_jenkins_builds_stage_duration_milliseconds_summary_count and default_jenkins_builds_stage_duration_milliseconds_summary_sum

**Jenkins Version**: 2.204.2

**Plugin Version**: 2.0.6

### Notify

@markyjackson-taulia

**Comment by perostman** [comment]
I checked in 2.08, and this does not seem to be fixed.
As mentioned in #177, #177 only contains a partial fix for this one. It still remains to produces metrics (duration) for each stage?

The `default_jenkins_builds_stage_duration_milliseconds_summary_sum/count` does not seem to produce per-run metrics?

**Comment by jj522** [comment]
I have checked 2.08 too, and this does not seem to be fixed. The duration for each stage is not in the metrics. 

If you got it working, can you please tell me the jenkins version and prometheus plugin version you are using? Thanks!
