### ISSUE TITLE
Getting "-1" for vm_memory_non_heap_max

### ISSUE THREAD

**Issue by akshayraut211** [jenkinsci/prometheus-plugin#154]
### Steps to reproduce
How can we reproduce the issue
1. Check the value for "vm_memory_non_heap_max" for Jenkins after the prometheus plugin is installed.

### Expected behaviour
Should Give a non-negative Valid value

### Actual behaviour
Give "-1" as value, which in turn give invalid value(greater than one)for  vm_memory_non_heap_usage
 
### Server configuration

**Operating system**: Ubuntu 18.04

**Jenkins Version**: 2.222.1

**Plugin Version**: 2.0.6

### Notify

@markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
This is not enough to go on here. Please provide screenshots and how to reproduce
