### ISSUE TITLE
Unable to change endpoint to /metrics

### ISSUE THREAD

**Issue by mvineza** [jenkinsci/prometheus-plugin#156]
### Steps to reproduce
How can we reproduce the issue
1. Go to settings and change Path to "metrics"
![image](https://user-images.githubusercontent.com/28911125/82868100-985a0500-9f5e-11ea-8b45-9cef0ec82290.png)

2. Hit apply
3. Try to access /metrics endpoint

### Expected behaviour
It should return exposed metrics.
![image](https://user-images.githubusercontent.com/28911125/82868187-cc352a80-9f5e-11ea-9d16-9db1c44103b7.png)

### Actual behaviour
I get 404 instead.
![image](https://user-images.githubusercontent.com/28911125/82868165-c0e1ff00-9f5e-11ea-9a97-8116df3ed423.png)
Using other names like "abc" or "sample" works fine. Seems the issue is isolated on "metrics".

### Server configuration

**Operating system**: CentOS Linux release 7.6.1810 (Core)

**Jenkins Version**: 2.222.3

**Plugin Version**: 2.0.6

### Notify

@markyjackson-taulia

**Comment by eryajf** [comment]
same question

**Comment by markyjackson-taulia** [comment]
This tells me you do not have metrics set on your Prometheus scrape config..

**Comment by Nemric** [comment]
> This tells me you do not have metrics set on your Prometheus scrape config..

The screen capture of @mvineza is taken from a browser, so saying that is an error as this is the response from jenkins itself, not a prometheus scrape configuration problem.

I'd like do change the default `prometheus` path to `metrics` to, [that is the prometheus default path value ](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config), and I'm issuing the same behaviour.
I have same output from a browser than in prometheus
![image](https://user-images.githubusercontent.com/56299157/168845660-996d59c6-1d9d-426d-829b-9983e20ce95f.png)

I use the file service discovery from prometheus, so the path `/metrics` is defined at the `job` level, it means that I would have to create a job, a service discovery file only for jenkins

> Using other names like "abc" or "sample" works fine. Seems the issue is isolated on "metrics".

I give a try with `metric` or `metricss` and it works fine, it should work with `metrics` to, this is definitely a bug, please reopen :wink:

**Comment by acompton-slack** [comment]
This plugin exposes the metrics provided by the [Metrics plugin](https://github.com/jenkinsci/metrics-plugin), which itself uses `/metrics`. That's why you can't change it to that path, since it's already taken.
