### ISSUE TITLE
feature request: add job build stauts 

### ISSUE THREAD

**Issue by jenningsloy318** [jenkinsci/prometheus-plugin#16]
currently this plugin only expose the jenkins server itself metrics, when we monitor the jenkins, we also want to make sure that the job status can be scraped. just want to add the jobs status metrics to help monitor job status.

**Comment by lsjostro** [comment]
Thanks for the feedback! You can get job metrics (duration of all the build stages). With the recent PR #15 you can even filter by build results. But if want to have build results like job X was unsuccessful it should be fairly easy to add that metric as well. I'm happy to accept pull requests.

**Comment by pmarques** [comment]
@jenningsloy318 maybe this PR is what you need https://github.com/jenkinsci/prometheus-plugin/pull/25

**Comment by markyjackson-taulia** [comment]
This issue was taken care of #25, closing this out
