### ISSUE TITLE
[JENKINS-62815] Traversal doesn't work on parallel pipelines

### ISSUE THREAD

**Issue by nigelarmstrong-bc** [jenkinsci/prometheus-plugin#161]
### Steps to reproduce
Have a pipeline with at least one parallel section. Try to gather stage duration data. 

### Expected behavior
Stage duration data should be recorded

### Actual behavior
No stage duration data is recorded. (`traverseTree(flownodes)` returns `[]`)

### Server configuration

**Operating system**:

**Jenkins Version**:

**Plugin Version**:
2.0.7

### Suggested fix:
In this file. Switch from a `return False` to a `continue`. The same node can be run into twice if a parallel pipeline is uses. If it is encountered, it should be skipped instead of exiting early, but I have not tested this.
https://github.com/jenkinsci/prometheus-plugin/blob/9a473b0b14ebe5167ef58d8316eb3a2712d5289e/src/main/java/org/jenkinsci/plugins/prometheus/util/FlowNodes.java#L102-L107
```java
            for (final FlowNode next : parents) {
                if (visited.contains(getNodeId(next))) {
                    continue;
                }
                queue.add(next);
            }
```

### Notify

@markyjackson-taulia

~P.S. I'm unable to open a jira at the moment because of the issues with accounts on jenkins.io~
Jira issue is [JENKINS-62815](https://issues.jenkins-ci.org/browse/JENKINS-62815)

**Comment by nigelarmstrong-bc** [comment]
Actually, there is another bug:

https://github.com/jenkinsci/prometheus-plugin/blob/9a473b0b14ebe5167ef58d8316eb3a2712d5289e/src/main/java/org/jenkinsci/plugins/prometheus/util/FlowNodes.java#L98
```final List<FlowNode> parents = current.getParents();```

**Comment by victorlopezsalazar** [comment]
@nigelarmstrong-bc @markyjackson-taulia, could we contribute with a PR to fix the `node` vs `current` bug? It seems a straightforward fix for the bug.

**Comment by victorlopezsalazar** [comment]
> The same node can be run into twice if a parallel pipeline is uses

@nigelarmstrong-bc are you sure that this is the case? From my own testing on different pipelines each node in a parallel block gets its own different id. You are right though,  in saying that the traversal should continue instead of returning early, because the order in which the nodes are traversed is not guaranteed due to precisely parallel blocks.

**Comment by nigelarmstrong-bc** [comment]
When a parallel pipeline converges the parallel nodes will each have the same parent, so the parent will have been visited by the first parallel pipeline branch, and the function will return without visiting any other parallel branches. If there are only two parallel branches this will work fine, but with more than 2 it will fail.

**Comment by victorlopezsalazar** [comment]
In that case I think it only makes sense to exit from the `visitNode` method when the queue is empty. I'd pose to change it to:

```java
private static void visitNode(final FlowNode node, final List<FlowNode> stageNodes, final Set<Integer> visited) {
        final Queue<FlowNode> queue = new ArrayDeque<>();
        queue.add(node);
        while (!queue.isEmpty()) {
            final FlowNode current = queue.poll();
            final Integer id = getNodeId(current);
            if (visited.contains(id) ) {
                continue;
            }
            visited.add(id);
            if (isStageNode(current)) {
                stageNodes.add(current);
            }

            List<FlowNode> parents = current.getParents();
            if (parents == null){
                continue;
            }

            for (final FlowNode next : parents) {
                if (visited.contains(getNodeId(next))) {
                    continue;
                }
                queue.add(next);
            }
        }
    }
```
