### ISSUE TITLE
Build success and failure count should be monotonically increasing number

### ISSUE THREAD

**Issue by palamvmw** [jenkinsci/prometheus-plugin#163]
### Steps to reproduce
How can we reproduce the issue
1. Create a test job which runs regularly at least 10 times a day.
2. It should fail 30% of the time to build collect failure count
3. Check the failure and success count for the test job for a period of one week

### Expected behaviour
The count for success and failure should never decrease

### Actual behaviour
The count for success and failure drops for a couple of days in the week time period

### Server configuration

**Operating system**: Centos 7

**Jenkins Version**: 2.222.1

**Plugin Version**: 2.0.7 and 2.0.6 (tried on both)

### Notify

@markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
@palamvmw I cannot reproduce this

**Comment by marceloavilaoliveira** [comment]
Hi @markyjackson-taulia 

I'm having the same issue. The "default_jenkins_builds_success_build_count" and "default_jenkins_builds_failed_build_count" are decreasing, as you can see in the following example:

![counter_issue](https://user-images.githubusercontent.com/20242819/100000935-1a59a800-2da1-11eb-886a-7aa7aea19474.jpg)

I'm wondering if this could be related to the Jenkins "discard old builds" strategy (log rotation), is it possible?

Operating system: Ubuntu 18.04
Jenkins Version: 2.249.1
Plugin Version: 2.0.7

**Comment by markyjackson-taulia** [comment]
> Hi @markyjackson-taulia
> 
> I'm having the same issue. The "default_jenkins_builds_success_build_count" and "default_jenkins_builds_failed_build_count" are decreasing, as you can see in the following example:
> 
> ![counter_issue](https://user-images.githubusercontent.com/20242819/100000935-1a59a800-2da1-11eb-886a-7aa7aea19474.jpg)
> 
> I'm wondering if this could be related to the Jenkins "discard old builds" strategy (log rotation), is it possible?
> 
> Operating system: Ubuntu 18.04
> Jenkins Version: 2.249.1
> Plugin Version: 2.0.7

This could very well be related to that

**Comment by marceloavilaoliveira** [comment]
Does it count the successful/failed builds using the backlog? I thought it would increment the counters every time a build is finished.

A counter must never decrease. Let me know if you want that I open a new issue. Thanks a lot.

**Comment by marceloavilaoliveira** [comment]
Hi @markyjackson-taulia, why [the issue I've created for this](https://github.com/jenkinsci/prometheus-plugin/issues/191) was closed?

**Comment by markyjackson-taulia** [comment]
Because I cannot reproduce this and the issue went stale.

**Comment by judos** [comment]
Hello, please reopen this ticket.
Steps to reproduce:
- Set jenkins to throw away old builds. E.g. only keep 30 builds. (similar to screenshot below)
- make sure you already have 30 builds
- trigger another build
- metric counter stays still at 30 builds (this counter is really not working as it should)
- Now let's increase jenkins configuration to keep the oldest 32 builds (see screenshot)
- Trigger build
- Counter now increases to 31 (but will not go past 32!)
Let's now decrease the counter for fun:
- Delete a build in jenkins
- Counter goes down by 1
![grafik](https://user-images.githubusercontent.com/5525810/140231109-a2ecace5-ba55-4c6d-9dd2-47e64ef74b76.png)

The metric probably just uses the number of builds jenkins has stored. But the counter must be individually tracked such that it does not stall when there is a build limit set. (or also when builds are removed manually)

Workaround:
1. Remove the build limit in jenkins for the moment, this however causes jenkins to store excessive amount of information which is probably undesirable...
2. For monitoring I now just the use the "default_jenkins_builds_health_score" which is probably enough if you want an alarm.
