### ISSUE TITLE
Stage Metrics Missing

### ISSUE THREAD

**Issue by tbickford** [jenkinsci/prometheus-plugin#169]
Are there any additional plugins or setup configuration to have the staging metrics emitted?

### Steps to reproduce

1. Create a pipeline based job like: 
```
node {
    stage('my test stage') {
        echo "hello"
    }
    stage('another stage') {
        sh("sleep 2")
    }
}
```

### Expected behaviour

There should be prometheus metrics emitted for stage duration for a job - https://github.com/jenkinsci/prometheus-plugin/blob/eb1adb6cee1cc2299ed8a87f728c2db9e4aeae54/src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java#L153

### Actual behaviour

The stage metrics are not present at the metrics endpoint. 

### Server configuration

**Operating system**:
Docker (jenkins/jenkins) - Linux 4.19 amd64
**Jenkins Version**:
2.257
**Plugin Version**:
2.0.7

### Notify

@markyjackson-taulia

**Comment by ilsl** [comment]
Hi I just tried this but unfortunately, this update broke our prometheus plugin
<img width="1526" alt="Screenshot 2020-10-21 at 15 04 26" src="https://user-images.githubusercontent.com/9089050/96731575-4e5f3900-13af-11eb-8ce9-aff9c7fa29da.png">

Previous Working Plugin Version:
2.0.7

Broken Plugin Version:
2.0.8

Super excited about this feature though!
