### ISSUE TITLE
Refine the documentation for the plugin

### ISSUE THREAD

**Issue by markyjackson-taulia** [jenkinsci/prometheus-plugin#170]
Better documentation is needed for this plugin.

**Comment by aaishikasb** [comment]
I am working on fixing some grammatical errors and typo errors in the documentation. If you find my work satisfactory, please approve my pull request. Please notify me if there are any issues with my PR.

**Comment by aaishikasb** [comment]
Can you assign the issue to me? I am working on it.

**Comment by markyjackson-taulia** [comment]
Any update @aaishikasb
