### ISSUE TITLE
Minor Fixes in the Documentation in the lines of Grammatical Errors and Typos

### ISSUE THREAD

**Issue by aaishikasb** [jenkinsci/prometheus-plugin#171]
### Steps to reproduce
How can we reproduce the issue
1. foo
2. bar
3. foo

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Jenkins Version**:

**Plugin Version**:

### Notify

@markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
PR was closed due to going stale
