### ISSUE TITLE
Feature proposal: an extension point for Jenkins-Prometheus plugin

### ISSUE THREAD

**Issue by MindaugasLaganeckas** [jenkinsci/prometheus-plugin#174]
*This is not a bug report*

We use Jenkins-Prometheus plugin in our organization. We think it is a good plugin and we are happy users of it.
Now we think we would like to extend it with the metrics, that come from Github. At the moment we are interested in monitoring API rate limits for App/user tokens. But we are certain that more usecases will be in the scope in the future.

In order to accomplish our goal, we would need the access to the Github auth (for app/user) secrets. We think the best way would be if we start working on a new plugin, that specializes in Github related monitoring, e.g. Jenkins-Prometheus-Github plugin. We would like to propose that the new plugin extends the existing Jenkins-Prometheus plugin. So all the configuration, needed to access Github, would stay in the Github plugin. But all the Prometheus related stuff would stay in the current plugin, and the new Github plugin would simply contribute with the extensions.

In the Eclipse world, there is a concept call Extension Point system, where one Eclipse plugin can define the interface for the extension and than more specific plugins can contribute to it. My feeling is that Jenkins has a similar system, but I have not had the time to look it up yet.
What I mean in the technical terms is if we could register more collectors with `collectorRegistry.register`, where every collector would implement `io.prometheus.client.Collector`. Something like that.

What do you think? Would you propose a better way to solve our problem?

### Notify

@markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
Jenkins has the same concept of dependencies use that you are describing.
I think if you wanted to do this correctly, you would build a new plugin that relies on this one as a dependency.

**Comment by MindaugasLaganeckas** [comment]
@markyjackson-taulia : that is exactly my proposal. I will have a look at how Jenkins handles plugin related extensions and get back to you if any extra changes in your plugin are needed. :) Thanks for a quick response!

**Comment by jpbottinelli** [comment]
@MindaugasLaganeckas I came here to look for this exact request. If you're working on something, I'm very much interested. Please share it here once you have it or I'll have to do something similar, but it's a needed plugin.
Thanks!
