### ISSUE TITLE
alerting for failed jobs

### ISSUE THREAD

**Issue by rmie** [jenkinsci/prometheus-plugin#179]
Not sure if this is a dup to https://github.com/jenkinsci/prometheus-plugin/issues/138 if so, please close

For now it seems to be difficult to impossible (at least for me) to create one (and only one) alert in prometheus for a jenkins job failing multiple times in a row, as all alert conditions I was able to come up with (see below in actual behaviour) are clearing the alert condition during job execution. This creates issues down the road as a streak of consecutive failures creates a new alert after each execution (duplicate tickets etc.)

### Actual behaviour
The best solution I could come up with is alerting on either of both conditions
- _jenkins_builds_last_build_result_ == 0
- _jenkins_builds_last_build_result_ordinal_ > 0
but neither of both evaluates to false while a job is running. default_jenkins_builds_last_build_result becomes 1 and 
default_jenkins_builds_last_build_result_ordinal is -1 for a running job.

### Expected behaviour
Have a metric that exports the state similar to either _jenkins_builds_last_build_result_ or _jenkins_builds_last_build_result_ordinal_ but ignoring current execution. This means a previously failed job will still be reported as "failed" while it is running again.

### Notify
@markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
Dup of #138

**Comment by qixiaobo** [comment]
> 

same 2

**Comment by ni-fgenois** [comment]
I don't think this is a duplicate of https://github.com/jenkinsci/prometheus-plugin/issues/138. That ticket is about the status of individual stages, this one is about the status of the build.

We are running in the same problem as described above, we want to set alerts based on a certain condition, but as the `jenkins_builds_last_build_result_ordinal` and `jenkins_builds_last_build_result` values are modified when the job is running, it is causing alerts to toggle between OK and FAILED.

It would be nice to have a metric that only includes completed jobs, not running jobs.
