### ISSUE TITLE
Memory leak still

### ISSUE THREAD

**Issue by mbevc1** [jenkinsci/prometheus-plugin#183]
Can we please reopen #160 as 2.0.8 is still not resolving it?

```
Oct 20, 2020 7:51:49 AM hudson.init.impl.InstallUncaughtExceptionHandler handleException
WARNING: Caught unhandled exception with ID cb34e4da-4856-4d56-bd16-fd4e13a5621b
java.lang.OutOfMemoryError: Java heap space

Oct 20, 2020 7:52:29 AM hudson.init.impl.InstallUncaughtExceptionHandler handleException
WARNING: Caught unhandled exception with ID 6f9e8576-0195-423c-aa0d-90ec157768f5
java.lang.OutOfMemoryError: Java heap space

Oct 20, 2020 7:59:35 AM hudson.model.AsyncPeriodicWork doRun
INFO: Periodic background build discarder thread is still running. Execution aborted.
Oct 20, 2020 8:03:31 AM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
```

**Comment by markyjackson-taulia** [comment]
Kindly provide the steps to reproduce. I do not see this leak when following #160 which is why I closed

**Comment by mbevc1** [comment]
Steps are the same; bump the plugin and wait for a bit. CPU is hammered and eventually OOMs with ^^. Let me know if there is anything else that would help you. Thanks!

**Comment by markyjackson-taulia** [comment]
I cannot reproduce that @mbevc1

**Comment by mbevc1** [comment]
Hm, are you using latest LTS Jenkins? perhaps it's related to many repos what is exhausting resources here? :thinking:

**Comment by markyjackson-taulia** [comment]
I am using the latest LTS

**Comment by mbevc1** [comment]
Still an issue on 2.263.1

**Comment by mbevc1** [comment]
Still seeing it on latest 2.263.4

**Comment by markyjackson-taulia** [comment]
Please use latest release

**Comment by mbevc1** [comment]
Were there any changed coming with 2.277.1 that might fix this behaviour?

**Comment by markyjackson-taulia** [comment]
@mbevc1 Are you referring to Jenkin 2.277.1?

**Comment by markyjackson-taulia** [comment]
I tried to reproduce this issue as best I could and could not.

**Comment by mbevc1** [comment]
Yeah, let me give it a go next week and report back.

**Comment by markyjackson-taulia** [comment]
@mbevc1 thank you. have a good rest of the weekend

**Comment by mbevc1** [comment]
Runs on 2.0.9 and latest LTS Jenkins for couple of days and seems okay now :crossed_fingers: . Thanks!
