### ISSUE TITLE
Names & Labels for jenkins_node_*_builds Metrics

### ISSUE THREAD

**Issue by james-m-tubbs** [jenkinsci/prometheus-plugin#185]
### Steps to reproduce
The Jenkins node names are baked into the metric name making generic templates and queries impossible.
```
jenkins_node_my_node1_builds{quantile="0.5",} 0.640805186 (and other quantiles)
jenkins_node_my_node1_builds_count 99.0

jenkins_node_my_node2_builds{quantile="0.5",} 0.640805186 (and other quantiles)
jenkins_node_my_node2_builds_count 99.0
```

### Expected behaviour
The node name should be taken out of the metric name and into a label. This allows for templating of nodes statistics and prevents manual work when adding a new node.

```
jenkins_node_builds{quantile="0.5",node="my_node1"} 0.640805186 (and other quantiles)
jenkins_node_builds_count 99.0 {node="my_node2"} 

jenkins_node_builds{quantile="0.5"node="my_node2"} 0.640805186 (and other quantiles)
jenkins_node_builds_count{node="my_node2"} 99.0
```

### Server configuration

**Jenkins Version**: 2.235.5

**Plugin Version**: 2.0.8

### Notify

@markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
@james-m-tubbs this is the way we built it. I know it may not work for you but for others, it does.
I am open to finding a common ground but cannot change overall for 1 person.

**Comment by james-m-tubbs** [comment]
@markyjackson-taulia it's not so much for me - this is a metric naming best practice thing. Makes it a lot easier for PromQL users downstream, especially, in theory, with things like dynamic agents. 

That said though, deleting the old metrics names is going to break a bunch of existing user's dashboards. If we decide to implement i'm not sure how best to approach this. Keep old metrics with a deprecation warning? Behind a config flag maybe (i don't even know if we can do that).

**Comment by markyjackson-taulia** [comment]
I can add it to the roadmap but it will be FY21 Q2 before I get to that. The roadmap is set already.

**Comment by james-m-tubbs** [comment]
I don't mind sending a PR either!

**Comment by markyjackson-taulia** [comment]
Pr’s totally welcomed

**Comment by Eric-Fontana-Bose** [comment]
Can't you just add another option, something like "jenkins-prefix" which defaults to "jenkins"




jenkins_node_my_node1_builds

i.e. "jenkins-prefix: myjenkins" results in:
could become:

myjenkins_node_my_node1_builds

This would allow a single prometheus to scrape may jenkins and the metric sets would be distinguised by name,
or, alternatively, add a label:

jenkins_node_my_node1_builds{namepace="namespace"}

Since namespace is already configurable.

**Comment by james-m-tubbs** [comment]
@Eric-Fontana-Bose this is better suited to adding labels in Prometheus.yml, that way you can template based on team/env. As in

```
- label_values
    env : dev
  targets
    - jenkins_dev.domain.com
- label_values
    env: prd
  targets
    - jenkins_prd.domain.com
```

Then your query becomes
```
jenkins_metric{env="prd"}
```

(Sry for formatting, on mobile)

**Comment by james-m-tubbs** [comment]
Heads up - I took a quick look at this and it seems more difficult than I anticipated. 

The build node metrics are derived from Dropwizard + jenkins metrics plugin which means we'll either have to:
A) Pull the metric timer out of the jenkins plugin and build a custom metric for it `jenkins.node._XXX.builds` 
B) Intercept the response before it's sent and rewrite those specific endpoints

Leaning towards option B as it's a bit cleaner to implement
