### ISSUE TITLE
Metrics Plugin Operational metrics?

### ISSUE THREAD

**Issue by holybit** [jenkinsci/prometheus-plugin#19]
Is it possible to get any of the four categories of "Operational" metrics from the prometheus plugin? 

For example, using the metrics plugin you can get ping and healthcheck.

$JENKINS_URL/metrics/currentUser/ping
$JENKINS_URL/metrics/currentUser/healthcheck

But I don't think you can get ping and/or healthcheck from prometheus plugin?

ping and healthcheck would be very useful. Ping can be used to write a check against Prometheus to ensure the Jenkins server is up and healthcheck could be used for example to ensure disk-usage is sane.

**Comment by cburroughs** [comment]
For healthcheck, see `jenkins_health_check_count`, `jenkins_health_check_score` and friends.

How do you imagine `ping` being expressed?  Is there a case where the healthchecks would pass and be accessible, but ping would fail?

**Comment by jmcshane** [comment]
The ping from dropwizard seems to map to the prometheus `up` metric which would come by default when scrape occurs. I don't see a reason to include that within the metrics.

**Comment by markyjackson-taulia** [comment]
Closing this out
