### ISSUE TITLE
"Successful build count" and "Failed build count" counters are decreasing some times

### ISSUE THREAD

**Issue by marceloavilaoliveira** [jenkinsci/prometheus-plugin#191]
### Steps to reproduce
1. Create a test job which runs regularly.
2. Check the success and failed build count counters graph.

### Expected behaviour
The successful and failed counters must never decrease.

### Actual behavior
The successful and failed counters go up and down.

### Note
Possibly this could be related to the Jenkins "discard old builds" strategy (log rotation)

### Server configuration
Operating system: Ubuntu 18.04
Jenkins Version: 2.249.1
Plugin Version: 2.0.7

### Notify
@markyjackson-taulia

**Comment by marceloavilaoliveira** [comment]
An example of the issue:
![counter_issue](https://user-images.githubusercontent.com/20242819/100033983-01211d80-2dda-11eb-88b6-03fb43291b51.jpg)

**Comment by tskinn** [comment]
I'm still seeing this or has there been a fix?

**Comment by PJHRobles** [comment]
+1 any updates here?
