### ISSUE TITLE
Documentation for how to configure using JCasC

### ISSUE THREAD

**Issue by yabberyabber** [jenkinsci/prometheus-plugin#198]
This is really a question rather than an issue to be reported. I see that the prometheus-plugin supports configuration via the Configuration as Code plugin, but I don't see documentation anywhere explaining how to configure or explaining what the field names are.

Is there documentation for this plugin other than the README?  @markyjackson-taulia, would you accept a PR which created a /docs directory at the root of this repo that just contains the JCasC info? Is there another location where this documentation would make more sense?

**Comment by markyjackson-taulia** [comment]
@yabberyabber 
Documentation has been really crap and I take full responsibility. My goal for Q1 FY21 is to change that.  I would love a pr but I have a hard time burdening people with shit I should be doing. With that being said, no this isn't documented and I really apologize.
