### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by jsalinaspolo** [jenkinsci/prometheus-plugin#199]
Could we make a new release to able to get the fix https://github.com/jenkinsci/prometheus-plugin/pull/192  ?

**Comment by markyjackson-taulia** [comment]
New release is coming this week

**Comment by tommartensen** [comment]
@markyjackson-taulia Thanks for your work on this plugin! Would you be able to give an ETA for the next release? We are also waiting for the fix from #192 .

**Comment by jsmilani** [comment]
We are waiting for the next release too. We just don't get any metrics data due to mysterious null pointer exceptions. We are currently stuck without monitoring.

**Comment by EusebiusAditya** [comment]
Are there any updates regarding this new release?

**Comment by nigelarmstrong-bc** [comment]
Any update on this release? We are also waiting on the fix from #192

**Comment by billygoo** [comment]
@markyjackson-taulia Thank you all the time. Do you have a release plan? I want to patched(#192) release version.
