### ISSUE TITLE
Currently "default_jenkins_builds_success_build_count" and "default_jenkins_builds_failed_build_count" metrics gives job specific build status for 4 status (i.e, for Success, Unstable, Failed and Aborted). Can we have 4 different count metric for all the build status?

### ISSUE THREAD

**Issue by ppthegp** [jenkinsci/prometheus-plugin#201]
### Expected behaviour
There should be 4 different metric for all the build status count i.e count for success, unstable ,failed and aborted. 

### Actual behaviour
Currently there are only two metric names "default_jenkins_builds_success_build_count" and "default_jenkins_builds_failed_build_count". The first one give count of success + unstable and second one give count of failed + aborted. All the four build status should have their own counter. 

### Server configuration

**Jenkins Version**: Jenkins 2.235.4

**Plugin Version**: 2.0.7

### Notify

@markyjackson-taulia

**Comment by KKC28** [comment]
Yes, if there are 4 different count for each state success, failure, unstable, aborted it would be good for capturing job statuses.

**Comment by markyjackson-taulia** [comment]
New release should fix
