### ISSUE TITLE
empty response due to thousands of kept job histories

### ISSUE THREAD

**Issue by cukal** [jenkinsci/prometheus-plugin#207]
This might help someone when faced with an empty response but no errors.

I had the same issue with 2.0.8 null pointer for empty parameter jobs, I upgraded to a (locally build) 2.0.9 and that fixed the null pointer in the logging but I was still getting an empty response, but no errors.
After enabling a log recorder on ```org.jenkinsci``` it reported gathering stats for really old flows, turns out Jenkins had some jobs that kept builds forever hence the exporter was busy appending them.

After running a cleanup script in Jenkins to remove the (thousands...) of kept builds the endpoint responded again with stats.

**Comment by rgrizzell** [comment]
My organization is experiencing the same issue. Our Jenkins organizational project has a lot repositories and the old builds are coming from SCM branches that haven't been deleted/closed.

While going through all of these projects and cleaning up the old branches is a good idea, it seems to be a bit much for a workaround to this problem.
