### ISSUE TITLE
Jenkins Metrics are coming in JSON format not in Prometheus format

### ISSUE THREAD

**Issue by poshak003** [jenkinsci/prometheus-plugin#209]
I have installed Prometheus Metrics plugin in Jenkins and configured the Job in Prometheus Yaml file and the endpoint is up in the Prometheus Monitoring page. When I enter the Jenkins url in the browser, metrics are coming in JSON format not in Prometheus format. Can someone please help me to fix this. 

Jenkins Version : 2.249.3
Prometheus Plugin Version: 2.0.8

Below is the document I have followed.

**https://github.com/jenkinsci/metrics-plugin**

Thanks

**Comment by Aki-7** [comment]
I thought you might have accessed to `$JENKINS_URL/metrics/$KEY/` like `https://your.host.com/metrics/currentUser`?

The correct endpoint for Prometheus is `$JENKINS_URL/prometheus` by default.
(see https://plugins.jenkins.io/prometheus/)

`$JENKINS_URL/metrics/$KEY/` is the endpoint for [Metrics](https://metrics.dropwizard.io/4.1.2/).

**Comment by markyjackson-taulia** [comment]
> I think you might access to `$JENKINS_URL/metrics/$KEY/` like `https://your.host.com/metrics/currentUser`.
> 
> The correct endpoint for Prometheus is `$JENKINS_URL/prometheus` by default.
> (see https://plugins.jenkins.io/prometheus/)
> 
> `$JENKINS_URL/metrics/$KEY/` is the endpoint for [Metrics](https://metrics.dropwizard.io/4.1.2/).

This is correct
