### ISSUE TITLE
Number of failed jobs

### ISSUE THREAD

**Issue by giotab** [jenkinsci/prometheus-plugin#210]
### Feature Request

Metric if there are any jobs which are currently in failed state.

Currently we have to check each job separately, but we generate jobs automatically which makes it difficult to keep track.
Instead, one metric which is "0/1" (or sum the jobs' results) indicating how many jobs are currently in failed state would be helpful.

**Comment by msven** [comment]
I think you can achieve this via a prometheus query using existing metrics.

For example to specifically target "failed" builds you could use

    count(default_jenkins_builds_last_build_result_ordinal == 2)

Otherwise, here is the list of the other ordinal values meanings if you want to get or combine other counts

        /*
         * _last_build_result _last_build_result_ordinal
         *
         * SUCCESS   0 true  - The build had no errors.
         * UNSTABLE  1 true  - The build had some errors but they were not fatal. For example, some tests failed.
         * FAILURE   2 false - The build had a fatal error.
         * NOT_BUILT 3 false - The module was not built.
         * ABORTED   4 false - The build was manually aborted.
         */

**Comment by giotab** [comment]
@msven so it is possible to use `default_jenkins_builds_last_build_result_ordinal` without specifying a specific `jenkins_job` to aggregate over all instances?

**Comment by msven** [comment]
Yes.

You can either leave the prometheus filter off to aggregate over all the data (as I had done in my example) or you can add a prometheus filter on to the query to filter down to whatever subset you desire.

For example, if you want to filter down to a subset of jobs in a particular folder you can do something like

    count(default_jenkins_builds_last_build_result_ordinal{ jenkins_job =~ "myFolderName/.+" } == 2)

**Comment by giotab** [comment]
Perfect, that's what I was looking for.

Thanks!
