### ISSUE TITLE
Release new update

### ISSUE THREAD

**Issue by markyjackson-taulia** [jenkinsci/prometheus-plugin#231]
This will release a new update

**Comment by markyjackson-taulia** [comment]
Plugin has been release and will take an hour or so to be available in the update center.
Sorry for the delay y'all

**Comment by fasatrix** [comment]
> Plugin has been release and will take an hour or so to be available in the update center.
> Sorry for the delay y'all

Hey @markyjackson-taulia thanks for this , however I do believe version 2.0.9 has not been publish yet? We build Jenkins image automatically and install latest plugins by default. Please take a look at he follows Thanks again

https://updates.jenkins.io/download/plugins/prometheus/

![image](https://user-images.githubusercontent.com/16127426/111920895-6a017380-8af6-11eb-9f13-886730d79175.png)

**Comment by markyjackson-taulia** [comment]
@fasatrix update center is slow but it has been released, as seen in artifactory [here](https://repo.jenkins-ci.org/webapp/#/artifacts/browse/tree/General/releases/org/jenkins-ci/plugins/prometheus/2.0.9/prometheus-2.0.9.hpi)

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/16655670/111921579-8b108880-8a52-11eb-9631-4539dd0a3e82.png">

**Comment by fasatrix** [comment]
> @fasatrix update center is slow but it has been released, as seen in artifactory [here](https://repo.jenkins-ci.org/webapp/#/artifacts/browse/tree/General/releases/org/jenkins-ci/plugins/prometheus/2.0.9/prometheus-2.0.9.hpi)
> 
> <img alt="image" width="1129" src="https://user-images.githubusercontent.com/16655670/111921579-8b108880-8a52-11eb-9631-4539dd0a3e82.png">

Thanks @markyjackson-taulia, it mean I will have to wait. Cheers
