### ISSUE TITLE
default_jenkins_builds_build_start_time_milliseconds not available after upgrading to 2.0.9 version

### ISSUE THREAD

**Issue by natarajanmurukan** [jenkinsci/prometheus-plugin#238]
### Version report

Jenkins and plugins versions report:

Jenkins: 2.285
OS: Linux - 3.10.0-514.21.2.el7.x86_64
---
prometheus:2.0.9

- What Operating System are you using (both controller, and any agents involved in the problem)?
Centos

### Reproduction steps

I have upgraded prometheus plugin from 2.0.8 to 2.0.9 and after upgradation, I am not able see the below metrics 

default_jenkins_builds_build_start_time_milliseconds
default_jenkins_builds_build_result
default_jenkins_builds_build_result_ordinal

1. Login into Jenkins as administrator
2. Manage Jenkins
3. Manage Plugins
4. Click on Available
5. Select Prometheus Metrics plugin
6. Install pluign and restart jenkins
7. Check the prometheus endpoint by accessing HTTP://yourjenkins.com/prometheus and verify below metrics available or not
default_jenkins_builds_build_start_time_milliseconds
default_jenkins_builds_build_result
default_jenkins_builds_build_result_ordinal
 

### Results
Not avaialable
Expected result:
The below metrics should be available for each job
default_jenkins_builds_build_start_time_milliseconds
default_jenkins_builds_build_result
default_jenkins_builds_build_result_ordinal

Actual result:

No metrics available with above metric name

**Purpose of the above metrics:**
Those metrics are used to find out the jobs executed in particular duration in Grafana dashboard using prometheus as datasource.

**Comment by msven** [comment]
These metrics which were introduced in version 2.0.8 were specifically removed in 2.0.9 because the number of timeseries they generated caused the plugin to stop working when there was a large number of builds in jenkins.

The following metrics are present, do they work for you?

default_jenkins_builds_last_build_duration_milliseconds
default_jenkins_builds_last_build_result
default_jenkins_builds_last_build_result_ordinal

**Comment by markyjackson-taulia** [comment]
A new release has been put out that will address this
