### ISSUE TITLE
Build parameter as separate metric label

### ISSUE THREAD

**Issue by mashinarius** [jenkinsci/prometheus-plugin#239]
### Dependencies
no

### Feature Request
In some cases one Jenkins job is used for building different components and we need to track metrics for each component individually.
There is a suggestion to add build parameters as a separate metric label

e.g.  we have a Jenkins job "job1"
this job contains string parameter "variable1"

```
default_jenkins_builds_duration_milliseconds_summary_count{jenkins_job="job1",repo="NA",status="SUCCESS",variable1="component1",} 1.0</br>
default_jenkins_builds_duration_milliseconds_summary_sum{jenkins_job="job1",repo="NA",status="SUCCESS",variable1="component1",} 596.0</br>
default_jenkins_builds_duration_milliseconds_summary_count{jenkins_job="job1",repo="NA",status="SUCCESS",variable1="component2",} 1.0</br>
default_jenkins_builds_duration_milliseconds_summary_sum{jenkins_job="job1",repo="NA",status="SUCCESS",variable1="component2",} 542.0</br>
```

appropriate pull request will be created.

Please review. Thank you!

**Comment by markyjackson-taulia** [comment]
A new release has been put out that will address this
