### ISSUE TITLE
Option to disable VM metrics

### ISSUE THREAD

**Issue by danpalmer** [jenkinsci/prometheus-plugin#24]
We're using the Prometheus plugin to monitor build times, and have no interest in the metrics for the JVM instance Jenkins runs on.

An option to disable these would be very useful to:

a) avoid polluting the global namespace of metrics
b) avoid storing metrics that we don't need to scrape.

**Comment by jeffersongirao** [comment]
@danpalmer you can drop metrics you do not want at scrape time, check  https://www.robustperception.io/dropping-metrics-at-scrape-time-with-prometheus/

**Comment by markyjackson-taulia** [comment]
Closing this out
