### ISSUE TITLE
Add gathering failed stages in job and status of stage

### ISSUE THREAD

**Issue by stru4OK** [jenkinsci/prometheus-plugin#252]
### Feature Request

Good afternoon!
We really have a need to gather information about failed stages as well in order to distinguish which stages in job were successful and which were failed. 
I found this fragment of code in method 'observeStage' of class 'JobCollector.java' where, I guess, are excluded failed stages on purpose:

```
        if (stage.getStatus() == StatusExt.SUCCESS || stage.getStatus() == StatusExt.UNSTABLE) {
            logger.debug("getting duration for stage[{}] in run [{}] from job [{}]", stage.getName(), run.getNumber(), job.getName());
            long duration = stage.getDurationMillis();
            logger.debug("duration was [{}] for stage[{}] in run [{}] from job [{}]", duration, stage.getName(), run.getNumber(), job.getName());
            stageSummary.labels(labelValueArray).observe(duration);
        } else {
            logger.debug("Stage[{}] in run [{}] from job [{}] was not successful and will be ignored", stage.getName(), run.getNumber(), job.getName());
        }
```
1. Is it possible to include also failed stages in job? If not - maybe add special global parameter for it?
2. Is it possible to add status of stage in metrics?
Thank you and have a nice day!

**Comment by stru4OK** [comment]
Should we create pull request for it?

**Comment by markyjackson-taulia** [comment]
This would need to be a feature request. I will not be adding any more new features until after May. I am using May to clean up tech debt. I will add this to the roadmap though.

**Comment by stru4OK** [comment]
Good morning!
Thank you, Marky Jackson! I'll be waiting for this feature to be included in new releases after May!

**Comment by juliantcook** [comment]
I was looking at getting stage level success metrics and came across this, has this been implemented? If not, is it something I could create a PR to add? Thanks
