### ISSUE TITLE
Unstable builds reported as failure

### ISSUE THREAD

**Issue by YonaLugassi** [jenkinsci/prometheus-plugin#271]
I'm using the metrics `default_jenkins_builds_failed_build_count` for counting specific job failures using the label `status` (status="FAILURE").
Builds with unstable status reported as a failure, I expect that build with unstable status will be tagged as UNSTABLE or reported as different metrics to count unstable builds
I want to count only the failures build and I can't, is there any way to configure the plugin to do so?

**Comment by markyjackson-taulia** [comment]
This does not currently exist
