### ISSUE TITLE
Jenkins job duration metrics filterable by enabled / disabled status

### ISSUE THREAD

**Issue by juanpablo-santos** [jenkinsci/prometheus-plugin#279]
### Feature Request

We have some dashboards showing the amount of time spent by various jobs, it would be nice if those could be filtered so only enabled jobs are shown, i.e.: being able to do something like: 
`topk( 10, default_jenkins_builds_last_build_duration_milliseconds{jenkins_job=~"myapp.*", enabled="true"} )`

**Comment by markyjackson-taulia** [comment]
Care to open an PR?

**Comment by juanpablo-santos** [comment]
Hi,

sure, doesn't seem like something especially difficult.. however, some guidance on where to touch would be greatly appreciated. I suppose [JobCollector#appendJobMetrics](https://github.com/jenkinsci/prometheus-plugin/blob/master/src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java#L246) is the place to go, but I'm not familiar with Jenkins / Prometheus internals, so any advice would be more than welcome.


thx + best regards,
juan pablo

**Comment by markyjackson-taulia** [comment]
Yes, that is the place. And thank you
