### ISSUE TITLE
Feature request: Add metrics for UP and UPTIME

### ISSUE THREAD

**Issue by ivan-pinatti** [jenkinsci/prometheus-plugin#28]
It would be nice to have these metrics exposed as well, it could be as:

- jenkins_up
- jenkins_uptime

Cheers!

**Comment by cburroughs** [comment]
How would `jenkins_uptime` be different from `vm_uptime_milliseconds`?

**Comment by ivan-pinatti** [comment]
Hi @cburroughs,

I haven't used this for a while.
However, if I recall correctly, two things:

1 - It is being standardized in other Prometheus scrapers to use the uptime as the metric for the **container uptime**, the `vm_uptime_milliseconds` is the java vm uptime. I know that they will basically mean the same thing in the end, but then there is the reason below as well.

2 - I guess the other uptime metrics were in seconds and not in miliseconds

Also, the feature request also asks for the **up** metric, which would be use to identify if the container was spontaneously rebooted and would trigger an alert through AlertManager.
