### ISSUE TITLE
Plug-in up for adoption

### ISSUE THREAD

**Issue by markyjackson-taulia** [jenkinsci/prometheus-plugin#307]
Due to recent family medical problems, I can no longer maintain this plugin and would like to put it up for adoption.
If you are interested, let me know via this issue.
Thanks kindly.

**Comment by sfryffdc** [comment]
How much effort would you say this involves, in practice?

**Comment by markyjackson-taulia** [comment]
@sfryffdc I would say 5 to 10 hours a week
