### ISSUE TITLE
Expose stage level success metrics

### ISSUE THREAD

**Issue by juliantcook** [jenkinsci/prometheus-plugin#309]
### Feature Request

We would like the ability to expose stage level metrics for our builds via the prometheus plugin.

---

It looks like this was already mentioned here: https://github.com/jenkinsci/prometheus-plugin/issues/252 

However I can't tell from the issue whether this is something that would be done or not.

Would it be possible for me (or someone at my current place of work) to raise a PR to add this functionality? Or would we need to fork the plugin with the desired functionality for use at our oganisation?

Thanks

**Comment by markyjackson-taulia** [comment]
@juliantcook who is `we`?

**Comment by markyjackson-taulia** [comment]
@juliantcook you are more than welcome to submit a PR. Happy to review. Also, if you are interested (or anyone in your organization), I would love to publicize a roadmap if I could get the input.
Happy to move this to a `discussion`
