### ISSUE TITLE
Export job build number as counter

### ISSUE THREAD

**Issue by costela** [jenkinsci/prometheus-plugin#31]
Right now, the easiest way to detect a build event (AFAICT) is to check `jenkins_builds_last_build_result_ordinal{exported_job="SOMEJOB"} == -1`. If you want - for instance - to add annotations to grafana based on this metric, this kinda works, as long as the job runs long enough for a scrape to "see" it.
A more robust way would be to export the build number, which should be monotonically increasing, as a counter. This could include currently running builds, because it would be relatively easy to filter out failing jobs (if that's what you want) by matching against `jenkins_builds_last_build_result_ordinal`.

**Comment by markyjackson-taulia** [comment]
This has been included on subsequent releases
