### ISSUE TITLE
Running job runtime

### ISSUE THREAD

**Issue by Spritekin** [jenkinsci/prometheus-plugin#318]
### Feature Request

I would like to alert when a job is taking too long to finish. I have tried metrics like default_jenkins_builds_build_duration_milliseconds and default_jenkins_builds_last_build_duration_milliseconds, however they seem to register a value only when the job has finished, not when a job is still running.

In fact, I can't see no new data saved for a job currently running, then I can't check a running job status.

How to reproduce
The following job just sleeps for one million seconds. I would be expecting to see a new metric value in prometheus with the current job duration every prometheus scrape period... but I see nothing until I stop the job in which case it displays the final runtime. I would like to see the intermediate values.

```
- script: >
    pipelineJob('test-running-job-metrics') {
      description("Check a running job current duration and status.")
      definition {
        cps {
          script('''\
            #!/usr/bin/env groovy
            def label = "test-job-metrics"
            podTemplate(
                label: label,
                containers: [
                    containerTemplate(
                        name: 'test-job-metrics',
                        image: 'debian:latest',
                        alwaysPullImage: true,
                        command: 'cat',
                        ttyEnabled: true
                    ),
                ]
            ) {
                node(label) {
                    dir(workdir) {
                        stage('Docker Build') {
                            container('test-job-metrics') {
                                sh """
                                env echo "Running running container metrics..."
                                sleep 1000000
                                exit 1
                                """
                            }
                        }
                    }
                }
            }
          '''.stripIndent())
          sandbox()
        }
      }
    }
```

Is this possible? Am I using the wrong metric maybe?

Regards,
Guimo

**Comment by Spritekin** [comment]
Just a bit more info. This is a screenshot from prometheus on the default_jenkins_builds_last_build_duration_milliseconds metric.

<img width="1740" alt="Screen Shot 2021-11-10 at 2 13 12 pm" src="https://user-images.githubusercontent.com/13467740/141042999-d4021201-01c7-42d0-887d-f91239ec460b.png">

The yellow line in the top right is a job I left running for 8 minutes. My Prometheus is configured to scrape every 60s, therefore there should be 8 metrics building up to the 8 minutes but there is nothing. Only when I stopped the job the metric appeared.

I'm running Jenkins 2.303.1 and Prometheus 2.28.1.

**Comment by raisalpa** [comment]
@markyjackson-taulia I am also looking for the same feature for this plugin. If this in place I could trigger an alert to our slack channel for immediate action.

**Comment by mushycode** [comment]
@raisalpa @Spritekin Were you able to get the metrics for running builds or is this still a missing feature?

**Comment by Spritekin** [comment]
> @raisalpa @Spritekin Were you able to get the metrics for running builds or is this still a missing feature?

No sorry never got a solution for this one
