### ISSUE TITLE
Add AlertManager rules for this plugin as an example

### ISSUE THREAD

**Issue by sneko** [jenkinsci/prometheus-plugin#319]
Hi @markyjackson-taulia ,

I'm currently having some troubles with builds being laggy/stuck so I started considering adding `prometheus-plugin`.

For other tools I already use Prometheus when necessary and often the tool shows example or Alertmanager rules so we get notified of weird behavior of the tool.

My question is: do you use Alertmanager to get notified of Jenkins issues? And if so, could you share those rules so it's easier to benefit from the plugin?

Thank you 😃 ,

**Comment by markyjackson-taulia** [comment]
I do not use alert manager for Jenkins.

**Comment by corporate-gadfly** [comment]
@sneko : See some alerts [here](https://awesome-prometheus-alerts.grep.to/rules.html#jenkins).
