### ISSUE TITLE
/prometheus endpoint does not redirect correctly

### ISSUE THREAD

**Issue by AndreaGiardini** [jenkinsci/prometheus-plugin#32]
Hello

The `/prometheus` endpoint is not redirecting correctly to `/prometheus/`. The redirect works well most of the time, but in our case (prometheus and jenkins running on kubernetes) the url returned is wrong, as you can see from the following screenshot.

![auswahl_0085](https://user-images.githubusercontent.com/3543138/34298307-6c5fdc78-e71d-11e7-919c-b4ef8c070f72.png)

The url:

`https://kubernetes.default.svc:443/api/v1/namespaces/ci/pods/jenkins-builder-0:8080/proxy/prometheus`

Should redirect to:

`https://kubernetes.default.svc:443/api/v1/namespaces/ci/pods/jenkins-builder-0:8080/proxy/prometheus/`

And not:

`https://kubernetes.default.svc:443/prometheus/`

Workaround: scrape directly on `/prometheus/`, bypassing the redirect

Thanks to @cmur2 for providing help debugging the issue

**Comment by jmcshane** [comment]
This is a feature of the Stapler request redirects that happen inside the Jenkins core, rather than anything specific about the plugin. You could put an issue out on the Jenkins core repository to see if they would support these types of redirects.

**Comment by markyjackson-taulia** [comment]
Agree with @jmcshane
