### ISSUE TITLE
Monotonic counter decreases when builds roll off (expire)

### ISSUE THREAD

**Issue by tlkamp** [jenkinsci/prometheus-plugin#327]
- What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu bionic 

### Reproduction steps
- Create a build and run it a few times with both successes and failures
- Configure Jenkins to expire/discard old builds
- Observe that metrics that are counters go down (successful and failed builds for example)

### Results

Expected result:
- I expect that the counters only increase and do not go down when old builds are expired/discarded.

Actual result:
- The counters go down, which causes alerts based on these values to fire.

Example: I have an alert that fires when the failure rate over a moving window of time is high. For simplicity, let's say there have been 100 total builds. Then 20 builds roll off, so the counter shows that I have 80 total builds instead of the full 100. Since the number goes down, the `rate` function of Prometheus assumes there has been a reset (counter set to zero) and then there have been 80 builds executed in between scrapes. If there are any failures in the remaining 80, they will cause the alert to fire as Prometheus thinks that they've all occurred within the last scrape interval.

Related issues:
- https://github.com/jenkinsci/prometheus-plugin/issues/191 
- https://github.com/jenkinsci/prometheus-plugin/issues/163
- https://github.com/jenkinsci/prometheus-plugin/issues/6

It appears that the previous issues have been closed because they cannot be reproduced, but this is clearly an issue experienced by multiple users.

**Comment by markyjackson-taulia** [comment]
Thank you for detailing. The previous issue was closed because the information provided I could not reproduce. I will use your very good info and triage this.

**Comment by tlkamp** [comment]
I'm happy to help provide more details if you find yourself needing any.

**Comment by markyjackson-taulia** [comment]
> I'm happy to help provide more details if you find yourself needing any.

I will totally ping you.

**Comment by sig-piskule** [comment]
Hello. I am experiencing this as well, and it appears that this is still happening in Prometheus metrics Version 2.1.1 with Jenkins 2.387.1.

I installed Jenkins using the Jenkins Helm Chart, so it is nothing special. You should be able to reproduce by installing Jenkins from Helm chart, and perhaps running some jobs regularly for a few weeks.
