### ISSUE TITLE
Metrics for running builds duration

### ISSUE THREAD

**Issue by ludoviclehmann** [jenkinsci/prometheus-plugin#358]
### What feature do you want to see added?

In order to be able to identify long running jobs, we are looking for a metric to get the current running time elapsed for each build: waiting time in queue and total build time.
We were able to get the build time with this script:
```
def busyExecutors = Jenkins.instance.computers
                                .collect { 
                                  c -> c.executors.findAll { it.isBusy() }
                                }
                                .flatten()

busyExecutors.each { e -> 
  println('==============')
  println(e.getCurrentExecutable());
  println(e.getElapsedTime());

}

```

**Comment by markyjackson-taulia** [comment]
This will be fixed in the next release
