### ISSUE TITLE
Summaries doesn't contain _sum metrics

### ISSUE THREAD

**Issue by shamil** [jenkinsci/prometheus-plugin#36]
Summaries should have `_sum` metrics. 

I'm using the latest version of the plugin, but I don't see `_sum` metrics, see below. I do see `_count` ...

What could be the reason?

```
# HELP jenkins_job_waiting_duration Generated from Dropwizard metric import (metric=jenkins.job.waiting.duration, type=com.codahale.metrics.Timer)
# TYPE jenkins_job_waiting_duration summary
jenkins_job_waiting_duration{quantile="0.5",} 0.0
jenkins_job_waiting_duration{quantile="0.75",} 0.0
jenkins_job_waiting_duration{quantile="0.95",} 0.0
jenkins_job_waiting_duration{quantile="0.98",} 0.0
jenkins_job_waiting_duration{quantile="0.99",} 0.0
jenkins_job_waiting_duration{quantile="0.999",} 0.0
jenkins_job_waiting_duration_count 0.0
```

**Comment by markyjackson-taulia** [comment]
Newest release addresses this issue

**Comment by shamil** [comment]
@markyjackson-taulia which newest release?
I'm running version `2.0.0` and still experience this issue

**Comment by markyjackson-taulia** [comment]
huh? Let me reopen

**Comment by shamil** [comment]
I see this issue was closed, does this mean it's fixed in next release?

**Comment by markyjackson-taulia** [comment]
Yes, I am working through an artifact issue. Should be releasing this week
