### ISSUE TITLE
metric TYPE is defined after samples still in 2.0.11

### ISSUE THREAD

**Issue by morfien101** [jenkinsci/prometheus-plugin#375]
The same issue is reported in #245 #250 #314

The above closed issues seems to all show the same error. I can confirm that this is still the case in the latest available plugin `Version: 2.0.11`.

I have just installed the plugin and configured telegraf and confirm the issues are exactly as described in the above mentioned issues.

**Comment by jessejoe** [comment]
I wanted to confirm we are also still seeing the issue described in #314 with the latest version of the plugin:
```
2022-02-23T15:26:30Z E! [inputs.prometheus] Error in plugin: error reading metrics for https://jenkins.mydomain.com/prometheus: reading text format failed: text format parsing error in line 1820: second TYPE line for metric name "jenkins_node_builds", or TYPE reported after samples
```

Looks like #314 was going to be addressed by @markyjackson-taulia, but instead the issue was closed (possibly due to inactivity?) We had to downgrade to `v2.0.8`.

**Comment by Waschndolos** [comment]
Seems like https://github.com/jenkinsci/prometheus-plugin/commit/23419dcaf0d319f86138bba9d91673d8d6b421e3 brought it in. It's the MetricsFormatter. It changes the Prometheus format (https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md). Unfortunately I have no knowledge with this library, maybe there is a possiblility to rename metrics without modifying the String?

**Comment by Waschndolos** [comment]
Got it! Guess there must be a blank after the comma of `\"master\",` in org/jenkinsci/plugins/prometheus/util/MetricsFormatter.java:11 and 12 like:

`        formatString = formatString.replaceAll("jenkins_node_builds\\{(.*)} (.*)", "jenkins_node_builds{node=\"master\", $1} $2");
        formatString = formatString.replaceAll("jenkins_node_(.*)_builds\\{(.*)} (.*)", "jenkins_node_builds{node=\"$1\", $2} $3");`

**Comment by w-marco** [comment]
I am also experiencing this issue on 2.0.11. Could you publish 2.0.13 to the Jenkins Plugin Repository?
