### ISSUE TITLE
Drop metrics that can be derived from others easily

### ISSUE THREAD

**Issue by aitorpazos** [jenkinsci/prometheus-plugin#378]
### What feature do you want to see added?

When running busy Jenkins instances, I've found that there are certain time series that seem duplicated or at least seem to be easily replaced by small adjustment on PromQL queries.
Having these additional time series puts extra burden on prometheus scrapes and prometheus itself.

At this point we are seeing ~22MB per-scrape data transfer with the following distribution of time series for `default_jenkins_*`:
```
default_jenkins_builds_duration_milliseconds_summary_count   1609
default_jenkins_builds_duration_milliseconds_summary_created 1611
default_jenkins_builds_duration_milliseconds_summary_sum     1609
default_jenkins_builds_failed_build_count_created            1326
default_jenkins_builds_failed_build_count_total              1326
default_jenkins_builds_health_score                         17374
default_jenkins_builds_last_build_duration_milliseconds     17365
default_jenkins_builds_last_build_result                    34748
default_jenkins_builds_last_build_result_ordinal            17374
default_jenkins_builds_last_build_start_time_milliseconds   17374
default_jenkins_builds_last_build_tests_failing                18
default_jenkins_builds_last_build_tests_skipped                18
default_jenkins_builds_last_build_tests_total                  18
default_jenkins_builds_success_build_count_created            287
default_jenkins_builds_success_build_count_total              287
```

As low hanging fruits, I can replace `default_jenkins_builds_last_build_result` by `default_jenkins_builds_last_build_result_ordinal` and perform values grouping and mapping on the PromQL/presentation side. Similar applies to `default_jenkins_builds_duration_milliseconds_summary_count` and `default_jenkins_builds_(success|failed)_build_count_total` where I can stick to `default_jenkins_builds_duration_milliseconds_summary_count`. Saving those time series would already be a significant saving.

I am trying it myself from this change: https://github.com/aitorpazos/prometheus-plugin/commit/71f0d1fc39aa8bc68d54afd86ec9c317184d2285

**Comment by markyjackson-taulia** [comment]
This functionality does not exist currently
