### ISSUE TITLE
Timestamp of last build

### ISSUE THREAD

**Issue by quodt** [jenkinsci/prometheus-plugin#38]
Please return the timestamp of the last built of jobs. This is a very useful information for example on backup jobs.

Currently the metric `default_jenkins_builds_last_build_result` looks like this:

```
default_jenkins_builds_last_build_result{exported_job="backup"} 1
```

Something like a `timestamp` label would be very helpful to create alert rule based on that value. For example:

```
default_jenkins_builds_last_build_result{exported_job="backup", timestamp="1519377401996"} 1
```

Maybe this kind of information fits better to the metric `default_jenkins_builds_last_build_duration_milliseconds` but it would be just helpful to have this information available.

**Comment by circa10a** [comment]
@lsjostro I currently have `2.0.0` installed on my jenkins box, but am not seeing the timestamp metric. Is this only in `1.X` versions?

**Comment by lsjostro** [comment]
It should be there. Maybe @markyjackson-taulia can verify?

**Comment by markyjackson-taulia** [comment]
Yes, it should be

**Comment by markyjackson-taulia** [comment]
just verified it is there

**Comment by circa10a** [comment]
I guess I should mention I installed from the update center and didn't build the project.

**Comment by circa10a** [comment]
Which metrics should the timestamp label be a part of?

**Comment by circa10a** [comment]
@markyjackson-taulia I just built the plugin from src, then the timestamp metric was available. It's not however in the version that is available in the jenkins update center.

**Comment by markyjackson-taulia** [comment]
Ok,
Let me reopen this issue and investigate in the morning

**Comment by markyjackson-taulia** [comment]
@circa10a can you give this a try again?

**Comment by faikabouthalja** [comment]
@markyjackson-taulia the new version 2.0.4 still doesn't show on jenkins update center
