### ISSUE TITLE
unable to uninstall the plugin

### ISSUE THREAD

**Issue by fh-venkat** [jenkinsci/prometheus-plugin#395]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

mac os

### Reproduction steps

step1: go to jenkins 
step2: manage Jenkins -> Installed tab
step3: uninstall the prometheus after searching for that.

### Expected Results

should be uninstalled

### Actual Results

Uninstallation pending

**Comment by markyjackson-taulia** [comment]
Did you reboot Jenkins post uninstall @fh-venkat ?
