### ISSUE TITLE
Naming of variables...

### ISSUE THREAD

**Issue by lyda** [jenkinsci/prometheus-plugin#4]
I noticed that there variables like this:

```
jenkins_node_NODE_builds
jenkins_node_NODE_builds_count
jenkins_node_NODE_builds_sum
```

Variables like this are problematic. I suspect it's what "dropwizard metric" creates, but generally it would be better if NODE was in a label.

**Comment by LuboVarga** [comment]
+1, according best practices also prefix (default_) is not needed... https://prometheus.io/docs/practices/naming/

**Comment by lsjostro** [comment]
totally agree! But as you noticed the dropwizard exporter doesnt seem to support that. :(
PR's are always welcome if you find some spare time to fix it.

**Comment by strowi** [comment]
i guess this is related.. 

Exporter and Prometheus are running, and i can query all jenkins_* values except the ones below.. Is it possibly a problem with the "," at the end?

```
# TYPE default_jenkins_builds_duration_milliseconds_summary summary
default_jenkins_builds_duration_milliseconds_summary_count{job="XYZ",} 18.0
default_jenkins_builds_duration_milliseconds_summary_sum{job="XYZ2",} 530322.0
```

**Comment by bernhardcygan** [comment]
Same here. I can't get the metrics that start with default_* . Any thoughts ?

**Comment by bernhardcygan** [comment]
@lsjostro The "default_" prefix actually is done in the source code. Do you need a PR to get rid of this ?

**Comment by lsjostro** [comment]
Sure go a head!

**Comment by lsjostro** [comment]
Should at least be configurable

**Comment by jmcshane** [comment]
This appears to be related instead to the way that the dropwizard metrics exporter emits these metrics. You can submit a PR to that project to make that configurable if this is necessary.

**Comment by markyjackson-taulia** [comment]
Closing this out

**Comment by arthur-c** [comment]
@markyjackson-taulia is there a workaround ? I'm not able to scrape metrics with `default_` prefix as well.

**Comment by arthur-c** [comment]
I found the other related issues about the need of permissions.

As I use GitHub Auth and Kubernetes pod discovery for prometheus, I can't use the basic auth. My solution is to scrape Jenkins metrics from an internal pod, then expose them with the right annotations to be scraped by prometheus.

BTY, I block the exposed prometheus path with this addition config in the jenkins ingress:

```
      - backend:
          serviceName: nginx-ingress-default-backend
          servicePort: 80
        path: /prometheus
```

**Comment by markyjackson-taulia** [comment]
> @markyjackson-taulia is there a workaround ? I'm not able to scrape metrics with `default_` prefix as well.

I can see about a work around in the next release if that is ok
I am going to re open this so I can track against it

**Comment by wjoel** [comment]
For what it's worth, we added an option to disable those metrics in our fork at https://github.com/cognitedata/metrics-plugin/pull/1 - it's not the best way to do it, I'm sure, but works for us. Those additional metrics were a major issue, since we use the Kubernetes plugin and therefore get a lot of "computers" as Jenkins sees it.

I hope it will be useful to someone, even if it only ends up being used as inspiration for a proper fix.

**Comment by markyjackson-taulia** [comment]
New release covers this edge case
