### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by lsjostro** [jenkinsci/prometheus-plugin#42]
As I'm lacking time and not currently using jenkins that much, I'm now searching for a new maintainer(s). 

https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin
https://wiki.jenkins.io/display/JENKINS/Prometheus+Plugin

**Comment by bernhardcygan** [comment]
I am using the plugin in production and am interested to become maintainer. Will look into the provided link for adopting a plugin. My Jenkins infrastructure id is bcygan.

Cheers and thank you for being a maintainer so far!
Bernhard

**Comment by jmcshane** [comment]
I am using this plugin as well and am interesting in becoming a maintainer on this project. My jenkins infrastructure id is james_mcshane.

Thanks for your work creating this plugin!

**Comment by lsjostro** [comment]
@bernhardcygan @jmcshane Thats great! Can you guys have a look at PR #47?

**Comment by bernhardcygan** [comment]
I guess I was too late for the party.
