### ISSUE TITLE
Make Job metrics optional

### ISSUE THREAD

**Issue by scurvydoggo** [jenkinsci/prometheus-plugin#436]
### What feature do you want to see added?

I would like the job metrics that this plugin exposes to be made optional.

This is because it is a high-cardinality label which goes against Prometheus [best practices](https://prometheus.io/docs/practices/naming/):
> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

In our case, as we have thousands of jobs, the endpoint would time out and so we are unable to use this plugin.

Therefore, we would like to add a configurable checkbox to disable job-related metrics, and instead expose only the standard [Jenkins metrics](https://plugins.jenkins.io/metrics) which we require in order to monitor our service.

**Comment by sboardwell** [comment]
I would like to add that with this fix https://github.com/jenkinsci/prometheus-plugin/pull/439 the metrics are going to grow even more. Perhaps a PR would be in order.

**Comment by sboardwell** [comment]
By the way, you can also deactivate build metrics by un-checking the relative check boxes. See screenshot below: 
![image](https://user-images.githubusercontent.com/18284380/189326334-cb90e947-57c3-462a-a227-562a1e64f9c2.png)
