### ISSUE TITLE
Publish Release 2.0.13 to official Jenkins page 

### ISSUE THREAD

**Issue by Waschndolos** [jenkinsci/prometheus-plugin#440]
### What feature do you want to see added?

Hey there,

the latest release on the official jenkins page ([https://plugins.jenkins.io/prometheus/](https://plugins.jenkins.io/prometheus/)) still points to 2.0.11. Could you somehow publish the latest release 2.0.13 to the official plugin site? 

This would help us a lot :)

Thank you!

**Comment by markyjackson-taulia** [comment]
@Waschndolos yeah, I have to figure out how republishing the artifact to artifactory from that release build. I will work on that over the next 2 weeks. In the meantime, you can easily compile and have the same thing, this should not be a blocker.

**Comment by Waschndolos** [comment]
Ok perfect. Thank you for the quick response!

**Comment by joaoamaro-vakt** [comment]
hey @markyjackson-taulia, any update on this subject?

**Comment by markyjackson-taulia** [comment]
@joaoamaro-vakt you can also compile the hpi if needed faster, super easy

**Comment by TomTondeur** [comment]
Hi @markyjackson-taulia, just wanted to check if you've had any success getting the runner to behave. My environment is set up to pull from the official Jenkins page and it would be cumbersome to switch this out, so I'd rather not if I can get the latest updates with just a bit more patience :)

**Comment by markyjackson-taulia** [comment]
@TomTondeur this will be done by end of week (sun), I promise.

**Comment by markyjackson-taulia** [comment]
@TomTondeur 


![image](https://user-images.githubusercontent.com/16655670/204402330-d8312c15-f8a5-4926-b027-dd69613dad83.png)

**Comment by markyjackson-taulia** [comment]
This has been released. Awaiting it to show up in the update ctr but artifactory shows the artifact
