### ISSUE TITLE
Add a corresponding grafana dashboard in grafana labs

### ISSUE THREAD

**Issue by oneslideicywater** [jenkinsci/prometheus-plugin#443]
### What feature do you want to see added?

Given that prometheus monitoring stack is usually the prom + grafana. Is there any grafana dashboard I can import into grafana to see the metric of this plugin at the first glance.

**Comment by KamilWalczak-TomTom** [comment]
This should work:
https://grafana.com/grafana/dashboards/9964-jenkins-performance-and-health-overview/
