### ISSUE TITLE
refrain from using "job" as a label

### ISSUE THREAD

**Issue by cburroughs** [jenkinsci/prometheus-plugin#45]
`job` has a special meaning to Prometheus and using it as a label has [complicated consequences](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Cscrape_config%3E).  Either you can't use `job` to mean the Jenkins job (it is transformed to `exported_job`), or you can't use `job` to refer to the Prometheus Job, neither of which is good.  It also makes it difficult to create re-usable dashboards.

I think it would be better if this label were called `jenkins_job` or something similar.  However, I'm unsure about how to proceed with backwards compatibility.
 * (A) Change `job --> `jenkins_job`, so everyone has the new setting but existing queries will break.
 * (B) Add a config option, default to existing behavior.  Continues to be bad for anyone who isn't both a Prometheus expert and digging through config options.
 * (C) Add a config option, default to `jenkins_job`.  This gives everyone an escape latch at the cost of maintaining yet another configuration option.
 * (D) As (B) or (C), but immediately deprecate the setting;  `jenkins_job` will be the only option after a future release.

I think (D) might be the least bad, but I'm not clear on the consequences for the Jenkins plugin compatibility model.

**Comment by tamsky** [comment]
- (E) A v2.0 release includes notice of a **Breaking Change** from `job`->`jenkins_job`

**Comment by markyjackson-taulia** [comment]
Merged
