### ISSUE TITLE
document need for Job:Read permissions for some metrics

### ISSUE THREAD

**Issue by cburroughs** [jenkinsci/prometheus-plugin#46]
Access to the endpoint (ie `prometheus/`) which displays everything from the Metrics plugin is controlled by authentication and the `Metrics.VIEW`.

However, to calculate the "builds" metrics (such as `jenkins_builds_duration_milliseconds_summary_count`) requires a call along the lines of
```java
        Jenkins jenkins = Jenkins.getInstance();
        if (jenkins != null) {
            List<Item> items = jenkins.getAllItems();
            if (items != null) {
                for (Item item : items) {
                    Collection<? extends Job> jobs = item.getAllJobs();
```

Without the `Job.READ` permission this will return an empty collection and no "builds" metrics will be calculated or displayed.  I think this is likely the cause of some of the reports of missing metrics in #12.

**Comment by jwenz723** [comment]
I have jenkins installed in my EKS cluster with this prometheus plugin enabled. I confirmed that if I login to the jenkins UI then browse to the /prometheus endpoint that I am able to view the `namespace_jenkins_builds_*` metrics. If I logout of the UI and browse to the /prometheus endpoint then I am not able to view the `namespace_jenkins_builds_*` metrics, however, I am still able to view all other metrics.

Is there a way to configure my prometheus plugin to not require a login to view these metrics?

**Comment by markyjackson-taulia** [comment]
@jwenz723 you can set anonymous mode in prometheus and also not select prometheus authentication in Jenkins

**Comment by jwenz723** [comment]
@markyjackson-taulia is there documentation on how I can do this? If so, can you point me to where this documentation is located?

**Comment by markyjackson-taulia** [comment]
@jwenz723 In all honesty my documentation is lacking. I will work to fix that by the end of this week.

**Comment by markyjackson-taulia** [comment]
@jwenz723 I updated the documentation a but, let me know if this is still an issue
