### ISSUE TITLE
Tagged versions not being published to plugins.jenkins.io

### ISSUE THREAD

**Issue by lafrenierejm** [jenkinsci/prometheus-plugin#470]
### Jenkins and plugins versions report

N/A

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

Visit <https://plugins.jenkins.io/prometheus/#releases> in a browser.

### Expected Results

Versions 2.0.12 and 2.0.13 are listed since they are tagged in this repo.

### Actual Results

As of 2022-12-06, 2.0.11 is the latest version and neither 2.0.12 nor 2.0.13 is available.

### Anything else?

I saw the reply on https://github.com/jenkinsci/prometheus-plugin/issues/469 about the Jenkins update center being slow to pull in updates. I would _expect_ (though don't know for certain) that this is a separate issue since this concerns <https://plugins.jenkins.io> and applies to 2.0.12 as well as 2.0.13.

**Comment by Waschndolos** [comment]
Hi,
I could also provide testing /dev capabilities if you need some in the future. 
Regarding the release.. It doesn't appear to be deployed yet. At least here in Europe. Do you know if there are maybe multiple Jenkins Update Sites for different regions or so that maybe the syncing between the regions fail?

**Comment by lafrenierejm** [comment]
> Regarding the release.. It doesn't appear to be deployed yet. At least here in Europe.

I can confirm that I'm not seeing the two tagged versions yet in the US either.

**Comment by markyjackson-taulia** [comment]
https://github.com/jenkinsci/prometheus-plugin/releases/tag/prometheus-2.0.14
