### ISSUE TITLE
Make Release 1.14 available in https://plugins.jenkins.io/prometheus/

### ISSUE THREAD

**Issue by Waschndolos** [jenkinsci/prometheus-plugin#477]
### What feature do you want to see added?

I know things like that are anoying :), but the release still doesn't appear on https://plugins.jenkins.io/prometheus/. Would you check this again please? Maybe it's not in your hand? Should we raise a ticket somewhere else maybe?

**Comment by PayBas** [comment]
@markyjackson-taulia All the hard work of the dependabot is for naught if the releases don't actually make it to https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/prometheus/ and https://plugins.jenkins.io/prometheus/ ;)

I've had to resort to building releases locally and installing the `.hpi` manually.
The CI/CD settings of this repo could use some love.

**Comment by Waschndolos** [comment]
@markyjackson-taulia Maybe as a heads up. I've had to revert back to parent pom version 4.38 in order to be able to build a .hpi file. This was upgraded by the dependabot but seemed to broke the build. Maybe therefore we cannot see a release in the jenkins release page.

**Comment by markyjackson-taulia** [comment]
@Waschndolos would you be interested in becoming a maintainer of this plugin?

**Comment by Waschndolos** [comment]
@markyjackson-taulia I don't have much experience in the official Jenkins Ecosystem (just maintaining some plugins for my company), but I can get into this if you want. Happy to help. If you can point me to the documentation I can dig into this :)

**Comment by markyjackson-taulia** [comment]
@Waschndolos https://www.jenkins.io/security/for-maintainers/

https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/

https://www.jenkins.io/doc/developer/publishing/documentation/

**Comment by Waschndolos** [comment]
@markyjackson-taulia. Ok I probably need some more time to understand everything but if you want I can help with this plugin. Do you want to give me some permissions to the repo first or should I do the "Adopt a Plugin" steps?

**Comment by markyjackson-taulia** [comment]
@Waschndolos you have to go through the `Adopt a Plugin` steps so the perms can be changed on the backend.

**Comment by Waschndolos** [comment]
@markyjackson-taulia. Hope I did everything right. The plugin-prometheus.yml in repository-permissions-updater seemed to be outdated. I removed the previous developer. Seems that he/she's no longer having a github account. Group Announcement: [https://groups.google.com/g/jenkinsci-dev/c/ZGtoWRTU_r8](https://groups.google.com/g/jenkinsci-dev/c/ZGtoWRTU_r8)

**Comment by Waschndolos** [comment]
Would also be great if you can provide me a quick guide on which steps you usually perform to do a release :) I hope I can manage the rest of the process on my own then :)

**Comment by markyjackson-taulia** [comment]
@Waschndolos otnis very straight forward and you can follow this [guide](https://www.jenkins.io/doc/developer/publishing/releasing-manually/)
