### ISSUE TITLE
Latest 2.1.1 Fails to Load with jenkins 2.375.2

### ISSUE THREAD

**Issue by AHancher2022** [jenkinsci/prometheus-plugin#488]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```
Jenkins: 2.375.2
OS: Linux - 5.10.102.1-microsoft-standard-WSL2
---
prometheus:2.1.1
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins: 2.375.2
OS: Linux - 5.10.102.1-microsoft-standard-WSL2

### Reproduction steps

1. Upgrade Prometheus to version 2.1.1 from 2.0.12 (older commit)
2. Fails to load

### Expected Results

Should be able to run prometheus plugin with no errors after upgrading. 

### Actual Results

 WARNING h.ExtensionFinder$GuiceFinder$FaultTolerantScope$1#error: Failed to instantiate Key[type=org.jenkinsci.plugins.prometheus.config.PrometheusConfiguration, annotation=[none]]; skipping this component
jenkins-master_1        | com.google.inject.ProvisionException: Unable to provision, see the following errors:
jenkins-master_1        |
jenkins-master_1        | 1) [Guice/CanNotProxyClass]: Tried proxying PrometheusConfiguration to support a circular dependency, but it is not an interface.
jenkins-master_1        |
jenkins-master_1        | Learn more:
jenkins-master_1        |   https://github.com/google/guice/wiki/CAN_NOT_PROXY_CLASS
jenkins-master_1        |
jenkins-master_1        | 1 error
jenkins-master_1        |
jenkins-master_1        | ======================
jenkins-master_1        | Full classname legend:
jenkins-master_1        | ======================
jenkins-master_1        | PrometheusConfiguration: "org.jenkinsci.plugins.prometheus.config.PrometheusConfiguration"
jenkins-master_1        | ========================
jenkins-master_1        | End of classname legend:
jenkins-master_1        | ========================

### Anything else?

We are upgrading our Jenkins version and when we pull in the 2.1.1 new Prometheus plugin, we receive that error. I have dug through the documentation and our Configuration as code and have tried to see if there had been anything that had changed but haven't been able to find anything. Was just wondering if there was any advice or if this has been brought up before.

**Comment by Waschndolos** [comment]
Didn't see that one. Just returned from vacation. I'll look into that this week. Thank you for the report

**Comment by Waschndolos** [comment]
@AHancher2022 I just tried to reproduce the issue. I took a blank 2.346.1, installed Prometheus 2.0.11. Then Upgraded to  Jenkins 2.375.3 and Prometheus 2.1.1. I didn't get this error. Can you maybe check if there's an additional or maybe corrupt org.jenkinsci.plugins.prometheus.config.PrometheusConfiguration.xml in JENKINS_HOME? Maybe deleting this file and restart Jenkins helps?

**Comment by Waschndolos** [comment]
any comments?

**Comment by Waschndolos** [comment]
Since I cannot reproduce the issue I attempted to do a blackbox fix in https://github.com/jenkinsci/prometheus-plugin/tree/bugfix/488. Can anybody may test if that fixes this issue?

**Comment by Waschndolos** [comment]
Update. I've found a system where I have sporadic access to which can reproduce the issue. I guess I have the root cause pinned. I'll get back to it once I fixed it.

**Comment by AHancher2022** [comment]
Sorry For not responding, we have decided since it is not a prevention bug, and jenkins still spins up, to ignore it for now. Again my apologies.

**Comment by Waschndolos** [comment]
Yes it still works, nevertheless it's not nice. I think I found a solution. Will test this next week and then perform a release. Thank your for pointing out the bug!

**Comment by AHancher2022** [comment]
Thank you for fixing this! I saw the email. I will talk with my team to get this prioritized to pull this in! Thank you again.

**Comment by Waschndolos** [comment]
I'll release a 2.1.2 this week.
