### ISSUE TITLE
Detailed documentation about each metric

### ISSUE THREAD

**Issue by athamour1** [jenkinsci/prometheus-plugin#489]
### Describe your use-case which is not covered by existing documentation.

Greetings, 

I found this [page](https://github.com/jenkinsci/metrics-plugin/blob/master/README.adoc), where a brief explanation can be found for some metrics, but I can't find an explanation for all the metrics exposed such as `default_jenkins_builds_last_build_result_ordinal`.

Am I missing something? Is there a page where all of the metrics are explained?

Thank you in advance for your time.

**Comment by Waschndolos** [comment]
Hi,

this plugin provides metrics by metrics-plugins as well as self calculated metrics. The self calculated metrics are prefixed with default_jenkins* (by default). I don't think those metrics are documented yet (you can find a short summary on the /prometheus endpoint). I'll check if I can provide a detailed documentation in the future. In your case the ordinal is:

         * SUCCESS:   0 - The build had no errors.
         * UNSTABLE: 1  - The build had some errors but they were not fatal. For example, some tests failed.
         * FAILURE:    2  - The build had a fatal error.
         * NOT_BUILT: 3  - The module was not built.
         * ABORTED:   4  - The build was manually aborted.
