### ISSUE TITLE
Metrics for penultimate builds

### ISSUE THREAD

**Issue by athamour1** [jenkinsci/prometheus-plugin#490]
### What feature do you want to see added?

Hello,

I extract statistics from Jenkins with your plugin.

I have created a query in PromQL to check if a Jenkins job build time has increased by 50% from the average successful build time:

```
default_jenkins_builds_last_build_duration_milliseconds > 1.5 * (avg_over_time(default_jenkins_builds_last_build_duration_milliseconds[180d]) and default_jenkins_builds_last_build_result_ordinal == 0)
```

However, there is a problem with this query. The result is getting diluted over time because the query keeps adding each value from the time-series to the total average result. There may be values that haven't changed, but they keep adding.

I expected to create a query that calculates the 'delta' from the current successful build time against the previous one, but there doesn't seem to be a metric that represents the previous build (or I can't find it), so I ended up using the average_over_time.

Can you add a metric that provides information for the previous build (penultimate build time and status)?

Best Regards

**Comment by Waschndolos** [comment]
Just came back from vacation. I'll check your request in the next couple of days. Thanks!

**Comment by Waschndolos** [comment]
There is a Setting in the Configuration page where you can enable Metrics for each build (Pay attention to the Notes). Then you'll get a metric for each build like:

```
default_jenkins_builds_build_duration_milliseconds{job="A_Test_params",repo="NA",buildable="true",status="FAILURE",number="5",} 369.0
default_jenkins_builds_build_duration_milliseconds{job="A_Test_params",repo="NA",buildable="true",status="FAILURE",number="3",} 165.0


```

**Comment by athamour1** [comment]
Thank you very much, this helped me to resolve my issue.
