### ISSUE TITLE
Metric to show duration of running build

### ISSUE THREAD

**Issue by ns-gsa** [jenkinsci/prometheus-plugin#505]
### What feature do you want to see added?

We are looking for a way to create a Prometheus alert by writing an expression using metrics exposed under https://github.com/jenkinsci/prometheus-plugin/blob/master/docs/metrics/index.md. 

This Prometheus alert would report if there is any currently running job(s) that has been running for a very long time. 
for eg., for our case, it would be a job running for more than 5 hours.

Currently we have `default_jenkins_builds_last_build_duration_milliseconds` metric, which we looked at using, however that would also report jobs that are not currently running.

So would like to have a separate metric to report something like `default_jenkins_builds_running_build_duration_milliseconds` which would only be for jobs currently running at the moment.

**Comment by Waschndolos** [comment]
I'll check if it's possible
