### ISSUE TITLE
Gauge showing size of build history for a job (number of old builds)

### ISSUE THREAD

**Issue by laf0rge** [jenkinsci/prometheus-plugin#506]
### What feature do you want to see added?

PArticularly in jenkins instances with hundreds of jobs, it is sometimes easy to miss the expiration of old runs/artefacts.

Having a gauge for each job indicating the size of the job build history would offer an easy way to spot such situations.

Right now, one has to go to the jenkins jobs directory and count tthe number of sub-directories of the job/$job/builds directory with a shell script - a bit arcane when at the same time there's also prometheus metrics available for other things.

A possible extension would be to not just count the size of the history in number of builds, but also in disk space utilization.  Running/managing a jenkins instance with terrabytes of build artefacts from hundreds of build of hundreds of jobs would be much more convenient that way.

**Comment by Waschndolos** [comment]
Good point. (Would help me as a Jenkins Admin as well :D) I'll look in to that

**Comment by Waschndolos** [comment]
Implemented the first draft. Would you be ok with this?
`
default_jenkins_builds_available_builds_count{jenkins_job="test_job_1",repo="NA",buildable="true",} 5.0
`

Guess the disk utilization can be retrieved from `job_usage_bytes`

**Comment by Waschndolos** [comment]
Will be available with the next release

**Comment by laf0rge** [comment]
> Implemented the first draft. Would you be ok with this? `default_jenkins_builds_available_builds_count{jenkins_job="test_job_1",repo="NA",buildable="true",} 5.0`

yes, that would work for me, thanks!

> Guess the disk utilization can be retrieved from `job_usage_bytes`

Thanks or that hint. Intrestingly I can't find this metric in my prometheus. Will have to investigate why that is.

**Comment by laf0rge** [comment]
> > Guess the disk utilization can be retrieved from `job_usage_bytes`
> 
> Thanks or that hint. Intrestingly I can't find this metric in my prometheus. Will have to investigate why that is, _despite_ the "Collect disk usage" checkbox being set in the configuration.

```
WARNING o.j.p.p.DiskUsageCollector#collect: Cannot collect disk usage data because plugin CloudBees Disk Usage Simple is not installed: java.lang.NoClassDefFoundError: com/cloudbees/simplediskusage/QuickDiskUsagePlugin
```

Intreesting. The question is why the plugin dependency resolution doesn't catch hhat automatically.  But thanks for pointing me in the right direction!

**Comment by Waschndolos** [comment]
It's because ```cloudbees-disk-usage-simple``` is marked as optional for prometheus-plugin. In that way as a Jenkins Admin you're not forced to have it installed. The code in prometheus-plugin can handle it's absense.
