### ISSUE TITLE
Add 'Ignored metrics regexp' option to ignore specific metrics based on regexp

### ISSUE THREAD

**Issue by fciarla** [jenkinsci/prometheus-plugin#516]
### What feature do you want to see added?

Hello,

we have deployed 'prometheus-plugin' in production and in our configuration Docker cloud Jenkins plugin, generate dynamic metrics (useless for us). These dynamic metrics increase Prometheus Index. 

For this reason we suggest to add the **Ignored metrics regexp** option with a textbox where is possible to add a regexp for specifying the desired metrics.

### Upstream changes

Class: **DefaultPrometheusMetrics**
Method: **collectMetrics()**

```
String metricsToIgnoreRegexp = PrometheusConfiguration.get().getMetricsToIgnoreRegexp();

Enumeration<Collector.MetricFamilySamples> allMetrics = collectorRegistry.metricFamilySamples();

List<Collector.MetricFamilySamples> filteredMetrics = new ArrayList<Collector.MetricFamilySamples>();
while (allMetrics.hasMoreElements()) {
    Collector.MetricFamilySamples metricFamilySamples =  allMetrics.nextElement();
    if (! metricFamilySamples.name.matches(metricsToIgnoreRegexp)) {
        filteredMetrics.add(metricFamilySamples);
    }
}
Enumeration<Collector.MetricFamilySamples> filteredMetricsAsEnumeration = Collections.enumeration(filteredMetrics);
TextFormat.write004(buffer, filteredMetricsAsEnumeration);

cachedMetrics.set(buffer.toString());
```

**Comment by vytstank** [comment]
This would certainly help to reduce a number of metrics scraped that our org does not use. For individual job metrics currently it is ["all or nothing"](https://github.com/jenkinsci/prometheus-plugin/blob/f66ba6b4c08f84ba1649ed40a9db3c2d36d94f7e/src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java#L173) and if there are more of them with large number of different stages, metric count grows rather quickly with all the PRs, etc.

Would be awesome to have some filtering via allow/blocklist regex or something similar

**Comment by Waschndolos** [comment]
Don't you dare to stale it github :)

**Comment by Waschndolos** [comment]
In progress

**Comment by Waschndolos** [comment]
Will be available with the next release. Preview config: https://github.com/jenkinsci/prometheus-plugin/blob/master/docs/configuration/configuration.md
