### ISSUE TITLE
Include complete example metrics output in README

### ISSUE THREAD

**Issue by tamsky** [jenkinsci/prometheus-plugin#52]
I might use this module, but I don't know what I'll get until I do.

It would be helpful to know what metrics (and labels) are emitted.

Thanks!

**Comment by cvega** [comment]
Hello Marc,

Haven't talked to you in awhile fellow ex-overseer. I'll see if I can do anything on my end to get metrics/labels listed here. With that said, I'm pretty sure it exposes what you'll see here in the metrics plugin: [https://wiki.jenkins.io/display/JENKINS/Metrics+Plugin](https://wiki.jenkins.io/display/JENKINS/Metrics+Plugin)

In the meantime here is what the endpoint is actually exposing on my system minus the actual data:


\# TYPE jenkins_executor_count_value gauge
\# TYPE jenkins_executor_free_value gauge
\# TYPE jenkins_executor_in_use_value gauge
\# TYPE jenkins_health_check_count gauge
\# TYPE jenkins_health_check_inverse_score gauge
\# TYPE jenkins_health_check_score gauge
\# TYPE jenkins_job_averageDepth gauge
\# TYPE jenkins_job_count_value gauge
\# TYPE jenkins_node_count_value gauge
\# TYPE jenkins_node_offline_value gauge
\# TYPE jenkins_node_online_value gauge
\# TYPE jenkins_plugins_active gauge
\# TYPE jenkins_plugins_failed gauge
\# TYPE jenkins_plugins_inactive gauge
\# TYPE jenkins_plugins_withUpdate gauge
\# TYPE jenkins_project_count_value gauge
\# TYPE jenkins_project_disabled_count_value gauge
\# TYPE jenkins_project_enabled_count_value gauge
\# TYPE jenkins_queue_blocked_value gauge
\# TYPE jenkins_queue_buildable_value gauge
\# TYPE jenkins_queue_pending_value gauge
\# TYPE jenkins_queue_size_value gauge
\# TYPE jenkins_queue_stuck_value gauge
\# TYPE system_cpu_load gauge
\# TYPE vm_blocked_count gauge
\# TYPE vm_class_loaded gauge
\# TYPE vm_class_unloaded gauge
\# TYPE vm_count gauge
\# TYPE vm_cpu_load gauge
\# TYPE vm_daemon_count gauge
\# TYPE vm_deadlock_count gauge
\# TYPE vm_file_descriptor_ratio gauge
\# TYPE vm_gc_PS_MarkSweep_count gauge
\# TYPE vm_gc_PS_MarkSweep_time gauge
\# TYPE vm_gc_PS_Scavenge_count gauge
\# TYPE vm_gc_PS_Scavenge_time gauge
\# TYPE vm_memory_heap_committed gauge
\# TYPE vm_memory_heap_init gauge
\# TYPE vm_memory_heap_max gauge
\# TYPE vm_memory_heap_usage gauge
\# TYPE vm_memory_heap_used gauge
\# TYPE vm_memory_non_heap_committed gauge
\# TYPE vm_memory_non_heap_init gauge
\# TYPE vm_memory_non_heap_max gauge
\# TYPE vm_memory_non_heap_usage gauge
\# TYPE vm_memory_non_heap_used gauge
\# TYPE vm_memory_pools_Code_Cache_committed gauge
\# TYPE vm_memory_pools_Code_Cache_init gauge
\# TYPE vm_memory_pools_Code_Cache_max gauge
\# TYPE vm_memory_pools_Code_Cache_usage gauge
\# TYPE vm_memory_pools_Code_Cache_used gauge
\# TYPE vm_memory_pools_Compressed_Class_Space_committed gauge
\# TYPE vm_memory_pools_Compressed_Class_Space_init gauge
\# TYPE vm_memory_pools_Compressed_Class_Space_max gauge
\# TYPE vm_memory_pools_Compressed_Class_Space_usage gauge
\# TYPE vm_memory_pools_Compressed_Class_Space_used gauge
\# TYPE vm_memory_pools_Metaspace_committed gauge
\# TYPE vm_memory_pools_Metaspace_init gauge
\# TYPE vm_memory_pools_Metaspace_max gauge
\# TYPE vm_memory_pools_Metaspace_usage gauge
\# TYPE vm_memory_pools_Metaspace_used gauge
\# TYPE vm_memory_pools_PS_Eden_Space_committed gauge
\# TYPE vm_memory_pools_PS_Eden_Space_init gauge
\# TYPE vm_memory_pools_PS_Eden_Space_max gauge
\# TYPE vm_memory_pools_PS_Eden_Space_usage gauge
\# TYPE vm_memory_pools_PS_Eden_Space_used gauge
\# TYPE vm_memory_pools_PS_Old_Gen_committed gauge
\# TYPE vm_memory_pools_PS_Old_Gen_init gauge
\# TYPE vm_memory_pools_PS_Old_Gen_max gauge
\# TYPE vm_memory_pools_PS_Old_Gen_usage gauge
\# TYPE vm_memory_pools_PS_Old_Gen_used gauge
\# TYPE vm_memory_pools_PS_Survivor_Space_committed gauge
\# TYPE vm_memory_pools_PS_Survivor_Space_init gauge
\# TYPE vm_memory_pools_PS_Survivor_Space_max gauge
\# TYPE vm_memory_pools_PS_Survivor_Space_usage gauge
\# TYPE vm_memory_pools_PS_Survivor_Space_used gauge
\# TYPE vm_memory_total_committed gauge
\# TYPE vm_memory_total_init gauge
\# TYPE vm_memory_total_max gauge
\# TYPE vm_memory_total_used gauge
\# TYPE vm_new_count gauge
\# TYPE vm_runnable_count gauge
\# TYPE vm_terminated_count gauge
\# TYPE vm_timed_waiting_count gauge
\# TYPE vm_uptime_milliseconds gauge
\# TYPE vm_waiting_count gauge
\# TYPE http_activeRequests gauge
\# TYPE jenkins_executor_count_history summary
\# TYPE jenkins_executor_free_history summary
\# TYPE jenkins_executor_in_use_history summary
\# TYPE jenkins_job_count_history summary
\# TYPE jenkins_node_count_history summary
\# TYPE jenkins_node_offline_history summary
\# TYPE jenkins_node_online_history summary
\# TYPE jenkins_project_count_history summary
\# TYPE jenkins_project_disabled_count_history summary
\# TYPE jenkins_project_enabled_count_history summary
\# TYPE jenkins_queue_blocked_history summary
\# TYPE jenkins_queue_buildable_history summary
\# TYPE jenkins_queue_pending_history summary
\# TYPE jenkins_queue_size_history summary
\# TYPE jenkins_queue_stuck_history summary
\# TYPE jenkins_servlet_container_active summary
\# TYPE jenkins_servlet_container_threadsCounter summary
\# TYPE jenkins_servlet_container_workers summary
\# TYPE jenkins_servlet_container_workersAcceptor summary
\# TYPE jenkins_servlet_container_workersSelector summary
\# TYPE jenkins_servlet_container_workersStatusBlocked summary
\# TYPE jenkins_servlet_container_workersStatusTimeWait summary
\# TYPE system_cpu_load_x100_history summary
\# TYPE vm_cpu_load_x100_history summary
\# TYPE vm_cpu_load_x100_window_15m summary
\# TYPE vm_cpu_load_x100_window_1h summary
\# TYPE vm_cpu_load_x100_window_5m summary
\# TYPE vm_file_descriptor_ratio_x100_history summary
\# TYPE vm_file_descriptor_ratio_x100_window_15m summary
\# TYPE vm_file_descriptor_ratio_x100_window_1h summary
\# TYPE vm_file_descriptor_ratio_x100_window_5m summary
\# TYPE vm_memory_heap_committed_history summary
\# TYPE vm_memory_heap_committed_window_15m summary
\# TYPE vm_memory_heap_committed_window_1h summary
\# TYPE vm_memory_heap_committed_window_5m summary
\# TYPE vm_memory_heap_usage_x100_history summary
\# TYPE vm_memory_heap_usage_x100_window_15m summary
\# TYPE vm_memory_heap_usage_x100_window_1h summary
\# TYPE vm_memory_heap_usage_x100_window_5m summary
\# TYPE vm_memory_heap_used_history summary
\# TYPE vm_memory_heap_used_window_15m summary
\# TYPE vm_memory_heap_used_window_1h summary
\# TYPE vm_memory_heap_used_window_5m summary
\# TYPE vm_memory_non_heap_committed_history summary
\# TYPE vm_memory_non_heap_committed_window_15m summary
\# TYPE vm_memory_non_heap_committed_window_1h summary
\# TYPE vm_memory_non_heap_committed_window_5m summary
\# TYPE vm_memory_non_heap_usage_x100_history summary
\# TYPE vm_memory_non_heap_usage_x100_window_15m summary
\# TYPE vm_memory_non_heap_usage_x100_window_1h summary
\# TYPE vm_memory_non_heap_usage_x100_window_5m summary
\# TYPE vm_memory_non_heap_used_history summary
\# TYPE vm_memory_non_heap_used_window_15m summary
\# TYPE vm_memory_non_heap_used_window_1h summary
\# TYPE vm_memory_non_heap_used_window_5m summary
\# TYPE vm_memory_pools_Code_Cache_committed_history summary
\# TYPE vm_memory_pools_Code_Cache_committed_window_15m summary
\# TYPE vm_memory_pools_Code_Cache_committed_window_1h summary
\# TYPE vm_memory_pools_Code_Cache_committed_window_5m summary
\# TYPE vm_memory_pools_Code_Cache_usage_x100_history summary
\# TYPE vm_memory_pools_Code_Cache_usage_x100_window_15m summary
\# TYPE vm_memory_pools_Code_Cache_usage_x100_window_1h summary
\# TYPE vm_memory_pools_Code_Cache_usage_x100_window_5m summary
\# TYPE vm_memory_pools_Code_Cache_used_history summary
\# TYPE vm_memory_pools_Code_Cache_used_window_15m summary
\# TYPE vm_memory_pools_Code_Cache_used_window_1h summary
\# TYPE vm_memory_pools_Code_Cache_used_window_5m summary
\# TYPE vm_memory_pools_Compressed_Class_Space_committed_history summary
\# TYPE vm_memory_pools_Compressed_Class_Space_committed_window_15m summary
\# TYPE vm_memory_pools_Compressed_Class_Space_committed_window_1h summary
\# TYPE vm_memory_pools_Compressed_Class_Space_committed_window_5m summary
\# TYPE vm_memory_pools_Compressed_Class_Space_usage_x100_history summary
\# TYPE vm_memory_pools_Compressed_Class_Space_usage_x100_window_15m summary
\# TYPE vm_memory_pools_Compressed_Class_Space_usage_x100_window_1h summary
\# TYPE vm_memory_pools_Compressed_Class_Space_usage_x100_window_5m summary
\# TYPE vm_memory_pools_Compressed_Class_Space_used_history summary
\# TYPE vm_memory_pools_Compressed_Class_Space_used_window_15m summary
\# TYPE vm_memory_pools_Compressed_Class_Space_used_window_1h summary
\# TYPE vm_memory_pools_Compressed_Class_Space_used_window_5m summary
\# TYPE vm_memory_pools_Metaspace_committed_history summary
\# TYPE vm_memory_pools_Metaspace_committed_window_15m summary
\# TYPE vm_memory_pools_Metaspace_committed_window_1h summary
\# TYPE vm_memory_pools_Metaspace_committed_window_5m summary
\# TYPE vm_memory_pools_Metaspace_usage_x100_history summary
\# TYPE vm_memory_pools_Metaspace_usage_x100_window_15m summary
\# TYPE vm_memory_pools_Metaspace_usage_x100_window_1h summary
\# TYPE vm_memory_pools_Metaspace_usage_x100_window_5m summary
\# TYPE vm_memory_pools_Metaspace_used_history summary
\# TYPE vm_memory_pools_Metaspace_used_window_15m summary
\# TYPE vm_memory_pools_Metaspace_used_window_1h summary
\# TYPE vm_memory_pools_Metaspace_used_window_5m summary
\# TYPE vm_memory_pools_PS_Eden_Space_committed_history summary
\# TYPE vm_memory_pools_PS_Eden_Space_committed_window_15m summary
\# TYPE vm_memory_pools_PS_Eden_Space_committed_window_1h summary
\# TYPE vm_memory_pools_PS_Eden_Space_committed_window_5m summary
\# TYPE vm_memory_pools_PS_Eden_Space_usage_x100_history summary
\# TYPE vm_memory_pools_PS_Eden_Space_usage_x100_window_15m summary
\# TYPE vm_memory_pools_PS_Eden_Space_usage_x100_window_1h summary
\# TYPE vm_memory_pools_PS_Eden_Space_usage_x100_window_5m summary
\# TYPE vm_memory_pools_PS_Eden_Space_used_history summary
\# TYPE vm_memory_pools_PS_Eden_Space_used_window_15m summary
\# TYPE vm_memory_pools_PS_Eden_Space_used_window_1h summary
\# TYPE vm_memory_pools_PS_Eden_Space_used_window_5m summary
\# TYPE vm_memory_pools_PS_Old_Gen_committed_history summary
\# TYPE vm_memory_pools_PS_Old_Gen_committed_window_15m summary
\# TYPE vm_memory_pools_PS_Old_Gen_committed_window_1h summary
\# TYPE vm_memory_pools_PS_Old_Gen_committed_window_5m summary
\# TYPE vm_memory_pools_PS_Old_Gen_usage_x100_history summary
\# TYPE vm_memory_pools_PS_Old_Gen_usage_x100_window_15m summary
\# TYPE vm_memory_pools_PS_Old_Gen_usage_x100_window_1h summary
\# TYPE vm_memory_pools_PS_Old_Gen_usage_x100_window_5m summary
\# TYPE vm_memory_pools_PS_Old_Gen_used_history summary
\# TYPE vm_memory_pools_PS_Old_Gen_used_window_15m summary
\# TYPE vm_memory_pools_PS_Old_Gen_used_window_1h summary
\# TYPE vm_memory_pools_PS_Old_Gen_used_window_5m summary
\# TYPE vm_memory_pools_PS_Survivor_Space_committed_history summary
\# TYPE vm_memory_pools_PS_Survivor_Space_committed_window_15m summary
\# TYPE vm_memory_pools_PS_Survivor_Space_committed_window_1h summary
\# TYPE vm_memory_pools_PS_Survivor_Space_committed_window_5m summary
\# TYPE vm_memory_pools_PS_Survivor_Space_usage_x100_history summary
\# TYPE vm_memory_pools_PS_Survivor_Space_usage_x100_window_15m summary
\# TYPE vm_memory_pools_PS_Survivor_Space_usage_x100_window_1h summary
\# TYPE vm_memory_pools_PS_Survivor_Space_usage_x100_window_5m summary
\# TYPE vm_memory_pools_PS_Survivor_Space_used_history summary
\# TYPE vm_memory_pools_PS_Survivor_Space_used_window_15m summary
\# TYPE vm_memory_pools_PS_Survivor_Space_used_window_1h summary
\# TYPE vm_memory_pools_PS_Survivor_Space_used_window_5m summary
\# TYPE vm_memory_total_committed_history summary
\# TYPE vm_memory_total_committed_window_15m summary
\# TYPE vm_memory_total_committed_window_1h summary
\# TYPE vm_memory_total_committed_window_5m summary
\# TYPE vm_memory_total_used_history summary
\# TYPE vm_memory_total_used_window_15m summary
\# TYPE vm_memory_total_used_window_1h summary
\# TYPE vm_memory_total_used_window_5m summary
\# TYPE http_requests summary
\# TYPE jenkins_health_check_duration summary
\# TYPE jenkins_job_blocked_duration summary
\# TYPE jenkins_job_buildable_duration summary
\# TYPE jenkins_job_building_duration summary
\# TYPE jenkins_job_queuing_duration summary
\# TYPE jenkins_job_total_duration summary
\# TYPE jenkins_job_waiting_duration summary
\# TYPE http_responseCodes_badRequest_total counter
\# TYPE http_responseCodes_created_total counter
\# TYPE http_responseCodes_forbidden_total counter
\# TYPE http_responseCodes_noContent_total counter
\# TYPE http_responseCodes_notFound_total counter
\# TYPE http_responseCodes_notModified_total counter
\# TYPE http_responseCodes_ok_total counter
\# TYPE http_responseCodes_other_total counter
\# TYPE http_responseCodes_serverError_total counter
\# TYPE http_responseCodes_serviceUnavailable_total counter
\# TYPE jenkins_job_scheduled_total counter
\# TYPE jenkins_runs_aborted_total counter
\# TYPE jenkins_runs_failure_total counter
\# TYPE jenkins_runs_not_built_total counter
\# TYPE jenkins_runs_success_total counter
\# TYPE jenkins_runs_total_total counter
\# TYPE jenkins_runs_unstable_total counter
\# TYPE totalLoggingOutputMeter_total counter
\# TYPE unrestrictedApiCallsMeter_total counter
\# TYPE default_jenkins_builds_duration_milliseconds_summary summary
\# TYPE default_jenkins_builds_last_build_result_ordinal gauge
\# TYPE default_jenkins_builds_last_build_result gauge
\# TYPE default_jenkins_builds_last_build_duration_milliseconds gauge

**Comment by tamsky** [comment]
Thanks Casey.   Definitely, long time no chat!

So it looks like, from your copypasta, that there are only named metrics an no labels?
This makes me wonder -- how are per-Job metrics exposed (or not?)

**Comment by yugansh20** [comment]
Hi 

Can we add above doc link (https://wiki.jenkins.io/display/JENKINS/Metrics+Plugin) in the Readme file . 
As there is not much doc on the attributes, it was very hard to find meaning of each metrics.

I found this link only when I started going through all the issues.

**Comment by markyjackson-taulia** [comment]
We are in hacktoberfest and I have a `good-first-issue` for documentation

**Comment by FelixKelm** [comment]
Why are the per-job metrics not described in the readme? Are they supported? Where do I find documentation about them?
e.g. I can find the metric default_jenkins_builds_last_build_result here https://github.com/jenkinsci/prometheus-plugin/issues/38 but no further documentation.
