### ISSUE TITLE
No known unit for task_waiting_duration and job_waiting_duration

### ISSUE THREAD

**Issue by macetw** [jenkinsci/prometheus-plugin#520]
### What feature do you want to see added?

We have quantiles for job-waiting, but we don't know what these values mean. It's not known what these units are. Are they fixed to a certain unit? We cannot tell what they are.

In the dropwizard documentation, it appears like the unit is something known to the API, but it doesn't get reflected in the Jenkins prometheus-plugin. See the "DurationUnit" as "milliseconds" in the following example illustrated.

https://metrics.dropwizard.io/3.2.3/getting-started.html#reporting-via-jmx

**Comment by macetw** [comment]
Also, it's not super clear what those specific metrics really mean to us. Is it about jobs waiting to find an idle Jenkins agent? Or are they about jobs waiting to be evaluated in Groovy by the jenkins-master?  Or something else?

**Comment by Waschndolos** [comment]
Back from vacation. Sorry for the late response :) Are you referencing "jenkins.job.waiting.duration" from https://github.com/jenkinsci/metrics-plugin?

**Comment by Waschndolos** [comment]
Closing issue as it appears to not be an issue anymore due to no response since may.

**Comment by sergeykad** [comment]
I have the same issue. Various metrics measure duration, but I couldn't find the documented units. My guess is milliseconds, but it would be great to have confirmation.

**Comment by Waschndolos** [comment]
Again, the jenkins.job.waiting.duration is received from the https://github.com/jenkinsci/metrics-plugin plugin. Looking at the code it appears to be milliseconds: https://github.com/jenkinsci/metrics-plugin/blob/86a20ba8318ba89d03cd2188aabe4dd00b4e7730/src/main/java/jenkins/metrics/impl/TimeInQueueAction.java#L64. For further references you may check in with the developer of that plugin
