### ISSUE TITLE
Problem with feature to disable certain metrics

### ISSUE THREAD

**Issue by Mohamed70** [jenkinsci/prometheus-plugin#554]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Container Debian GNU/Linux 11 (bullseye)

### Reproduction steps

1. Enable feature "Disable metrics"
2. Add Fully qualified Name Entry : jenkins_job_count_history
3. Add Regex entry: vm.*
4. Save

### Expected Results

The expected result is to disable metrics jenkins_job_count_history and all metrics starts with vm_* and to not have them on metrics in the page $jenkins_url/prometheus

### Actual Results

The configuration is saved correctly, but without any results, the metrics are not disabled, and I can still see them on $jenkins_url/prometheus

### Anything else?

I can see that the parameters is taken by the conf file on the jenkins machine:
```
<disabledMetricConfig>
    <entries>
        <org.jenkinsci.plugins.prometheus.config.disabledmetrics.NamedDisabledMetric>
            <metricName>jenkins_job_count_history</metricName>
        </org.jenkinsci.plugins.prometheus.config.dísabledmetrics.NamedDisabledMetric>
        <org.jenkinsci.plugins.prometheus.config.dísabledmetrics.RegexDisabledMetric>
            <regex>vm.*</regex>
        </org.jenkinsci.plugins.prometheus.config.dísabledmetrics.RegexDisabledMetric>
    </entries>
</disabledMetricConfig>
```

**Comment by Waschndolos** [comment]
Hi,
unfortunatelly this is currently not possible. You can only disable metrics which are calculated by prometheus-plugin itself. The output of the plugin also contains metrics from the metrics plugin (such as vm.). Those are not possible to disable. Check out the Release Notes: 
![image](https://github.com/jenkinsci/prometheus-plugin/assets/22710627/af64be0c-26a5-4290-b828-79550c57ba79)

**Comment by Waschndolos** [comment]
OK I think I found a way. I'll do further testing and release it in the next release

**Comment by Mohamed70** [comment]
Thanks a lot for your answer and for the fast update.
I tested it, it works! :)
