### ISSUE TITLE
No all_jenkins_version_info metric in 2.3.2 version

### ISSUE THREAD

**Issue by denix666** [jenkinsci/prometheus-plugin#557]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins: 2.414.1
OS: Linux - 3.10.0-1160.95.1.el7.x86_64
Java: 11.0.15 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)

### Reproduction steps

Go to https://path.to.jenkins/prometheus to get all the metrics

### Expected Results

Expecting to see the:
all_jenkins_version_info{version="2.414.1",} 1.0

### Actual Results

There is no any info about the versions

### Anything else?

Have a couple of dozen jenkins instances, and the issue appears only after installing this version of plugin.

**Comment by Waschndolos** [comment]
Thanks for the hint. Could you provide the output of an jscasc export for the prometheus section?   Or the xml file with the plugin configuration. I'll check asap then.

**Comment by denix666** [comment]
prometheusConfiguration:
    appendParamLabel: false
    appendStatusLabel: false
    collectCodeCoverage: false
    collectDiskUsage: true
    collectNodeStatus: true
    collectingMetricsPeriodInSeconds: 60
    countAbortedBuilds: true
    countFailedBuilds: true
    countNotBuiltBuilds: true
    countSuccessfulBuilds: true
    countUnstableBuilds: true
    defaultNamespace: "all"
    fetchTestResults: true
    jobAttributeName: "jenkins_dev201"
    path: "prometheus"
    perBuildMetrics: false
    processingDisabledBuilds: true
    useAuthenticatedEndpoint: false

**Comment by Waschndolos** [comment]
@denix666 Do you have a chance to test https://github.com/jenkinsci/prometheus-plugin/pull/558? Otherwise I'll install it in my companies Test Jenkins instance tomorrow.

**Comment by denix666** [comment]
Tested build from 23530b08c91b59c3bfcaa02df20dee3b62d4efe9 - can confirm that it works!

**Comment by Waschndolos** [comment]
Great thank you for your help. I've just released 2.3.3

**Comment by denix666** [comment]
Thanks a lot for the great work!
