### ISSUE TITLE
display job running on each agent

### ISSUE THREAD

**Issue by carocad** [jenkinsci/prometheus-plugin#564]
### Use case
I would like to know which agent is being used by which job

### Background
In my company we are trying to identify which projects are responsible for how much costs of the build agents. In order to do that we would like to correlate a job running with an agent being busy. Unfortunately to the best of my knowledge there is currently no way of knowing which job is being built in which agent.

### Proposal
I think adding a `jenkins_job ` label to the `default_jenkins_executors_busy` metric would solve this.

**Comment by Waschndolos** [comment]
Hi, thank you for the request. I would also love to have this but I don't think it's easily possible for pipeline jobs as (as far as i know) they don't have a direct relation to the host they're running on in the Model. I'll see what can be done (As I also need this :) ) but I can't promise. If you have an idea let me know

**Comment by Waschndolos** [comment]
@carocad. I looked into this. I cannot see a possibility to get this information. I could get the information from the Agent Object maybe but then you have the problem, that the scraper runs only every like 30seconds or so and you don't get a valid results bc you may have builds where parts are calculated on the machine, which may only run 10 seconds or so and you never get these. That would only raise more tickets here. 

The Jenkins Model doesn't provide such functionality to get the agent for a pipeline afaik. Guess the root problem is kown. See https://issues.jenkins.io/browse/JENKINS-47138 or https://issues.jenkins.io/browse/JENKINS-38877. Once it can be done (or anyone shows me how) I'll be more than happy to provide this functionality. Until then I need to reject this.

**Comment by carocad** [comment]
Hello @Waschndolos ,
Thanks a lot for looking into this and the fast response. It is a pity that this is not supported by Jenkins itself but I understand the reasoning.

I guess I will look into parsing the logs or the `build.xml` file which seems to contain this information.

Cheers
