### ISSUE TITLE
getting an error

### ISSUE THREAD

**Issue by jogeeswarbabu** [jenkinsci/prometheus-plugin#576]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

ubuntu 22.04lts

### Reproduction steps

1.prometheus plugin error getting
2.jenkins restarting issue 

### Expected Results

I hope to resolve this asap to get the service to utilise the Prometheus plugin 

### Actual Results

Getting an restarting error of Prometheus plugin and restarting

### Anything else?

no need

**Comment by Waschndolos** [comment]
And... What kind of error? Any logs available? Wich Version of the Plugin?

**Comment by Waschndolos** [comment]
Closing as incomplete
