### ISSUE TITLE
Support getting metrics for slaves/nodes/workers

### ISSUE THREAD

**Issue by victorb** [jenkinsci/prometheus-plugin#58]
We currently have about 15 workers running together with Jenkins + this Prometheus plugin for getting metrics.

It would be wonderful if this plugin could grab the same data as the `https://$JENKINS_HOST/computer/` view provides, for each worker.

The data I'm interested in getting is `free disk space` and also `response time`. If someone can provide pointers to how to implement this in the plugin, I'd be happy to give it a try.

**Comment by sa-spag** [comment]
Hello 👋 
This issue is closed even though it has not been addressed. Could you please update or re-open it? Thanks.
