### ISSUE TITLE
sum of total builds, successful builds and failed builds are resetting to 0, when jenkins got restarted

### ISSUE THREAD

**Issue by sachin6005** [jenkinsci/prometheus-plugin#588]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins is installed on RHEL7 server

### Reproduction steps

jenkins_runs_total_total
jenkins_runs_success_total
jenkins_runs_failure_total

These metrics values(count) is resetting to 0 when jenkins got restarted

### Expected Results

some particular count of total builds, success and failed builds

### Actual Results

resetting to 0 when Jenkins get restarted

### Anything else?

I dont see any retention period in the prometheus plugin configuration or any other option which helps me to resolve the issue of count resetting, please let me know if there is any option.
we need to total build counts per month, if there is retention period it would be useful to get the required count without resetting
please consider my request or help me if you have any solution to this issue.

Thankyou

**Comment by Waschndolos** [comment]
@sachin6005 This Plugin gets the metrics from the current state Jenkins is having. Once there is a restart of Jenkins any counters are lost. It's not intended by this plugin to save states across Jenkins restarts. 

Usually what you will do with this plugin is that you scrape the Prometheus Endpoint this Plugin is providing with telegraf, store it e.g. in an InfluxDB and get your results with a query within Influxdb (and probably visualize it with Grafana or any of such tooling). In the InfluxDB the historic measurements are stored then and you can get your desired results from there.
