### ISSUE TITLE
no timing for stages

### ISSUE THREAD

**Issue by arnitolog** [jenkinsci/prometheus-plugin#59]
I have several jobs which have stages inside. And I'm interested to have timing per stage as a metric.
According to the code, it looks like plugin already has such functionality. But de facto it doesn't expose these metrics. Tried with completely clean jenkins installation and simple pipelines like 'Hello world'. All checkboxes are checked in the plugin configuration. Have I missed something, or it simply doesn't support such metrics yet?

**Comment by ybrodskiy** [comment]
i'm having same issue. reading code cant' seems to figure out why they are not showing up

**Comment by markyjackson-taulia** [comment]
Ok, i’ll debug this on my end tonight

**Comment by ybrodskiy** [comment]
> Ok, i’ll debug this on my end tonight

@markyjackson-taulia, sorry to bug you... any luck on the issue?

**Comment by arnitolog** [comment]
I see some errors in the log file witch related to DropwizardExports. 
Attached file with the errors and other logs. 
[jenkins_log.txt](https://github.com/jenkinsci/prometheus-plugin/files/2459996/jenkins_log.txt)

**Comment by markyjackson-taulia** [comment]
Sorry for the delays. I was traveling for work. I am picking this back up
