### ISSUE TITLE
Job counters must never go down

### ISSUE THREAD

**Issue by aecolley** [jenkinsci/prometheus-plugin#6]
I have a job whose `default_jenkins_builds_duration_milliseconds_summary_sum` suddenly reduced from 4306 to 4277. This should never happen. Prometheus counters are supposed to accumulate events monotonically. The only time they can go down is when the server resets all of its statistics (e.g. at restart).

At the time of the change, the Jenkins job ran from a timer, creating a new build record and expiring the Nth oldest one (due to the Discard Old Builds option). I suspect that the prometheus plugin simply sums the times of the undiscarded builds. The latest one completed faster than the Nth-ago one, so the sum went down. The corresponding `_count` variable stayed constant, probably for the same reason.

Suggested fix: make proper counters and increment them when a new build completes.

Alternative fix: stop exporting these as counters, and change the help string to make it clear what they really are.

**Comment by lsjostro** [comment]
You're absolutly correct. We only iterate over non expired jobs. I don't see any easy way to do this though... The alt fix could absolutly be a temp fix. so if you find time I happy to merge a PR.

**Comment by markyjackson-taulia** [comment]
I will keep this open as a feature request and try to get it on the next release

**Comment by markyjackson-taulia** [comment]
New release covers this
