### ISSUE TITLE
I would like to help maintain this plugin after seeing it is up for adoption

### ISSUE THREAD

**Issue by markyjackson-taulia** [jenkinsci/prometheus-plugin#60]
@lsjostro I see you are currently the maintainer. Can we chat?

**Comment by markyjackson-taulia** [comment]
@lsjostro I put in an email to the Jenkins-Dev google group about adopting this plugin.

**Comment by markyjackson-taulia** [comment]
In the meantime if you comment here with your approval, it will start the process on the Jenkins org side: https://groups.google.com/forum/m/#!topic/jenkinsci-dev/VVjUBFmoJqg

**Comment by markyjackson-taulia** [comment]
Let me know when and how you would like to do the handover.

**Comment by markyjackson-taulia** [comment]
A polite ping about the handoff @lsjostro

**Comment by lsjostro** [comment]
sure thing @markyjackson-taulia, been busy on this end of the pool. Not much to handover though, just go through the issues and pull requests I guess. I'll approve you as the new maintainer and which you good luck with it.

**Comment by markyjackson-taulia** [comment]
Thank you kindly @lsjostro Once you do that I will resubmit my PR for permissions to the Jenkins permissions repo and verify that I have the needed rights. Finally I will then go through the issues and start prioritizing
