### ISSUE TITLE
Job distinction by assignedNode

### ISSUE THREAD

**Issue by Kudrixon** [jenkinsci/prometheus-plugin#600]
### What feature do you want to see added?

![image](https://github.com/jenkinsci/prometheus-plugin/assets/35082391/58b35249-6bad-4bda-a5e4-f32877c03db4)
I would love to sort my jobs by nodes assigned to them like I can sort them by repos

### Upstream changes

I've seen data about assignedNode in config.xml of job maybe that is the approach

**Comment by Waschndolos** [comment]
Hey @Kudrixon,

I would love to have this as well but unfortunately the jenkins model doesn't provide such information for pipeline jobs. 

The assignedNode only appears for Freestyle builds and this can also be a label with 300 nodes. 

So as long as the jenkins model don't provide such information in the build object I cannot provide this. All other attempts to get the node name like parsing it from the pipeline definition are just hacks and don't lead to a reliable solution. If anybody have a valid idea I'm glad to accept a PR for this. Until then I'm sorry to close the request.
