### ISSUE TITLE
Adding per build metrics data in stage

### ISSUE THREAD

**Issue by Saurabh111191** [jenkinsci/prometheus-plugin#603]
### What feature do you want to see added?

Hello ,

We are using jenkins prom plugin to measure each our stage , and we have a use case in which we want to measure each our stage performance based on build parameters or even if build number is there , we can join that data in grafana based on build number.  So is there any way we can per build metrics data in stage summary metrics also.

**Comment by Waschndolos** [comment]
Yes I'll check
