### ISSUE TITLE
Issues with namespace

### ISSUE THREAD

**Issue by Waschndolos** [jenkinsci/prometheus-plugin#615]
@Waschndolos we are currently testing this fix and surprinsingly, we now have an issue on the "namespace" (or "prefix") of some metrics that are still using the default namespace/prefix instead of using the one we configured in the options... 
could it be related ?

![image](https://github.com/jenkinsci/prometheus-plugin/assets/9500406/bc10e589-698b-46c7-b4e1-3dcb461a10a7)

For example, we configured jenkins to change the default namespace to "gtp" instead of "default" and some metrics are still named "default_xxx" whereas other have the right prefix.

![image](https://github.com/jenkinsci/prometheus-plugin/assets/9500406/f0bdb71d-8d01-4a39-8ce5-89e211699e1e)

After searching a bit in the code, we saw that some metrics methods are not using the "prefix" arguments here : https://github.com/jenkinsci/prometheus-plugin/blob/master/src/main/java/org/jenkinsci/plugins/prometheus/collectors/builds/BuildCollectorFactory.java#L18-L49

but it does not seem to match exactly the metrics for which we have the default prefix... so not so sure it comes from there.

Additionnal details : 
- jenkins version : 2.426.2
- prometheus plugin version : 2.5.0
- we are using Configuration-as-Code plugin to configure all our plugins, including the prometheus-metrics one.

_Originally posted by @yogeek in https://github.com/jenkinsci/prometheus-plugin/issues/606#issuecomment-1887448328_

**Comment by Waschndolos** [comment]
@aidanleuck: I think the error is here: org.jenkinsci.plugins.prometheus.collectors.builds.BuildCollectorFactory#createCollector#63

There the counter collector is only called once since it's a singleton. When somebody changes the namespace after a jenkins start the changes are not reflected. 

@yogeek. Can you confirm that it's working after you restart Jenkins?

**Comment by yogeek** [comment]
@Waschndolos indeed the namespace/prefix changes correspond to Jenkins restarts

**Comment by Waschndolos** [comment]
The prefix is the "_last" token. One could argue that it doesn't make sense on the counters as it's an overall metric.. Honestly, No clue. I took over that code. Probably doesn't hurt if we add it for all Build related metrics.

**Comment by aidanleuck** [comment]
@Waschndolos Yes the counter is a singleton, there is already some logic in the CounterManager.Java class that determines whether or not a new counter should be returned. Currently, it only looks at prefix, labels and the counter type. It Looks like namespace should also be added to that list to force a new counter to be created. If we just add a new field to CounterEntry and account for it in the equals/hashcode method this issue will be solved. Would you like to take this one or would you like me to open a PR?

**Comment by Waschndolos** [comment]
@aidanleuck  Currently I'm kind of short in time so I really would appreciate a PR :)

**Comment by aidanleuck** [comment]
@Waschndolos Will get that up in the next couple of days. The Counter will get reset to zero when a configuration change occurs since a new counter is returned. I think this is okay though since it is technically a new metric once the name has changed

**Comment by aidanleuck** [comment]
@Waschndolos I tackled this issue just now. PR coming shortly. A Namespace change does not modify the value of the counter so pretty cool. The previous comment about the counter resetting can be ignored.

**Comment by Waschndolos** [comment]
Looks like it could work :) I'll test it at the weekend and perform a bugfix release. Thank you for the quick fix!

**Comment by Waschndolos** [comment]
Tested in on our companies test jenkins - works +1

**Comment by yogeek** [comment]
Great thank you both!
Just waiting for the next release now 😉

**Comment by Waschndolos** [comment]
There you go: https://github.com/jenkinsci/prometheus-plugin/releases/tag/prometheus-2.5.1
