### ISSUE TITLE
When I install the plugin and restart Jenkins, accessing the/prometheus interface returns 404

### ISSUE THREAD

**Issue by jibingjie2** [jenkinsci/prometheus-plugin#617]
### Expected behaviour
Return metrics data

### Actual behaviour
![image](https://github.com/jenkinsci/prometheus-plugin/assets/101303865/a7724e10-2339-48f6-8e75-f4fc9af6fe60)

Plugin installed
![image](https://github.com/jenkinsci/prometheus-plugin/assets/101303865/1921b373-0879-4e44-b3bf-c3bd6b3bb920)

### Server configuration

**Operating system**:centos7.9

**Jenkins Version**:2.401.3

**Plugin Version**:2.5.0

### Notify

@Waschndolos

**Comment by Waschndolos** [comment]
I guess your endpoint is configured as /prometheus?

**Comment by jibingjie2** [comment]
> I guess your endpoint is configured as "/prometheus"? Any logs you can share or can you share a screenshot of your prometheus plugin configuration in Jenkins?

I just installed the plugin and restarted Jenkins without any other actions.

Do you need plugin configuration? Here, it is the default
![image](https://github.com/jenkinsci/prometheus-plugin/assets/101303865/61752e22-e233-4fbe-b00d-ca4786a6f724)

**Comment by Waschndolos** [comment]
Yes thank you. The issue is the path configuration here. That is the path where it is reachable in Jenkins. Just put "prometheus" in it and it will be reachable at http(s)://yourjenkins:(port)/(jenkins?)/prometheus

**Comment by Waschndolos** [comment]
Updated documentation here: https://github.com/jenkinsci/prometheus-plugin/blob/master/docs/configuration/configuration.md#path
