### ISSUE TITLE
Exclude organization scans etc. from job statistics

### ISSUE THREAD

**Issue by micxer** [jenkinsci/prometheus-plugin#62]
We are using this plugin to monitor all our Jenkins instances and were wondering why we have so many builds on weekends. After some digging we found that this plugin seems to not only count build jobs that are setup to build software but also Github organization scans and similar tasks that Jenkins runs once in a while. I didn't find a metric that only counts one or the other so it is impossible to have a graph that only shows "real" build jobs. Is there a way to do that which I didn't find or is it currently impossible to create such a graph?

**Comment by markyjackson-taulia** [comment]
@micxer I will try to recreate that and see

**Comment by markyjackson-taulia** [comment]
@micxer Can you try unchecking "Count duration of not-built builds"

**Comment by micxer** [comment]
@markyjackson-taulia I changed the setting and will have a look at it again tomorrow, to see, if it made a difference over night.

**Comment by micxer** [comment]
Didn't make difference unfortunately. Might be even a problem on my side calculating the numbers wrong. I will double-check the numbers again and reopen the ticket, if I still find something is wrong. Thanks.
