### ISSUE TITLE
Metric: plugins with vulnerabilities

### ISSUE THREAD

**Issue by ryoga86** [jenkinsci/prometheus-plugin#624]
### What feature do you want to see added?

Hello team,

is there any possibility to create a metric which counts amount of current installed plugins with known vulnerabilities?
thx in advance

![image](https://github.com/jenkinsci/prometheus-plugin/assets/13853329/f5a420dc-3d37-4f7e-8821-ead2abf546a4)

**Comment by Waschndolos** [comment]
@ryoga86. Good point here. But the metrics of the plugins are calculated in https://plugins.jenkins.io/metrics/. Can you raise an issue there. Once they have it it can be populated with this plugin

**Comment by ryoga86** [comment]
thx for your quick response. seems like they disabled issue section :/

**Comment by Waschndolos** [comment]
Maybe we should file a PR there. Guess the code to get plugins with warnings is: https://github.com/jenkinsci/jenkins/blob/ed8562fdf77c685ab25adfc304a6306b13b96638/core/src/main/java/jenkins/security/UpdateSiteWarningsMonitor.java#L81

**Comment by ryoga86** [comment]
already found a way to do feature request
https://issues.jenkins.io/browse/JENKINS-72647

**Comment by Waschndolos** [comment]
Created a PR: https://github.com/jenkinsci/metrics-plugin/pull/262

**Comment by Waschndolos** [comment]
Closing this PR as it's done in the metrics-plugin. Should work out of the box if they release a version with the feature so no actions to be done in this plugin.
