### ISSUE TITLE
Feature request: add build parameters as a job metric

### ISSUE THREAD

**Issue by michaelschr** [jenkinsci/prometheus-plugin#64]
Is it possible to add build parameters as a metrics per job?
Thanks.

**Comment by markyjackson-taulia** [comment]
This is possible, I will try to work this in to the up coming release

**Comment by michaelschr** [comment]
Thanks!

**Comment by perkrifj** [comment]
Hi guys!

Did this feature ever make? I've had a browse through the current project and can't find anything.
Having the build parameters available in one form or another would be really useful.
