### ISSUE TITLE
Exclude statistics for Build

### ISSUE THREAD

**Issue by sebastiangraf** [jenkinsci/prometheus-plugin#65]
Hi there,
We are facing an issue similar to https://issues.jenkins-ci.org/browse/JENKINS-44513

> It seems that from time to time the prometheus plugin is very slow to complete the requests for /prometheus.

We run this plugin in several instances of Jenkins, one containes more than 16000 jobs. In this setup, the plugin is not usable since the generation of the build stats bases on the global_build_stats-Plugin as you can see in the Thread Dump: It computes the stats upon request and simply takes too long.

![microsoftteams-image](https://user-images.githubusercontent.com/1047301/45608116-376fef00-ba51-11e8-8ccb-5062fbd86af5.png)

Is there any chance to make the inclusion of build stats optional?
regards
sebastian

**Comment by icereed** [comment]
@sebastiangraf we had the same issue on our instances. I proposed the PR #71 to solve this.

**Comment by sebastiangraf** [comment]
With the PR#71, that one can be closed.
