### ISSUE TITLE
Need Build_ID, build_number or job ID in output

### ISSUE THREAD

**Issue by vipin5050** [jenkinsci/prometheus-plugin#661]
### What feature do you want to see added?

I would like to have build_id, build_number or jenkins job ID to be collected by the prometheus. As I am thinking to have a metrics to do time taken by individual job ID, something like
<img width="997" alt="Screenshot 2024-05-09 at 11 23 30 AM" src="https://github.com/jenkinsci/prometheus-plugin/assets/79691636/546f824d-c9e7-4793-ba8b-8265c82efa65">
 

### Are you interested in contributing this feature?

I can test the builds or solution.

**Comment by Waschndolos** [comment]
Currently no Computer around, but the Plugin should already provide such Information. Looks you have a dedicated displayname in Grafana. Maybe temporary remove it from the Dashboard, then you should get the Information. If not i can take a closer Look on monday

**Comment by vipin5050** [comment]
I was looking in to metrics provided and I couldnt find Build_ID, build_number or job ID, I could be wrong if you can find that would be awesome. If not please try to include if reasonably possible.

**Comment by Waschndolos** [comment]
I will check on monday, currently on vacation.

**Comment by Waschndolos** [comment]
@vipin5050. Just checked it. When you use the Prometheus Plugin without any further configuration you'll only get the jenkins_job name as info. Like

`default_jenkins_builds_build_duration_milliseconds{jenkins_job="test",repo="NA",buildable="true"}`

 However there's an option in the configuration page: 

![image](https://github.com/jenkinsci/prometheus-plugin/assets/22710627/078eb6d4-b6af-46f4-bb71-d60c7a444cf0)

which also prints out the build number:

```
default_jenkins_builds_build_duration_milliseconds{jenkins_job="test",repo="NA",buildable="true",number="1",} 628.0
default_jenkins_builds_build_duration_milliseconds{jenkins_job="test",repo="NA",buildable="true",number="2",} 369.0
```

It will display all builds available, so if you have like 200 builds, you get 200 entries.
