### ISSUE TITLE
Option to get build count per job

### ISSUE THREAD

**Issue by eloo** [jenkinsci/prometheus-plugin#67]
At the moment it is only possible to get the build count of job by enabling time metrics for jobs.
But i've you're having a huge jenkins this will never be completed.. 
So it would be great if we could enable build count separate from the build times.

Thanks

**Comment by eloo** [comment]
@markyjackson-taulia is this now included?

**Comment by surendar-rajasekaran** [comment]
@markyjackson-taulia  Any update on this case?
