### ISSUE TITLE
403 Forbidden or Unauthorized errror: while trying to access (http://<jenkins_pubip>:Port/prometheus) path even trying with a Read user with API generated token, the issue persist. 

### ISSUE THREAD

**Issue by waseemshaik1993** [jenkinsci/prometheus-plugin#674]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu

### Reproduction steps

Install Promtheus plugin into Jenkins management console.

### Expected Results

NA

### Actual Results

![image](https://github.com/jenkinsci/prometheus-plugin/assets/96241675/f0881c7a-fe26-427a-bb2d-d57640a785eb)

### Anything else?

No

### Are you interested in contributing a fix?

Yes

**Comment by Waschndolos** [comment]
Did you check? https://github.com/jenkinsci/prometheus-plugin/blob/master/docs/configuration/configuration.md#enable-authentication-for-prometheus-end-point

**Comment by waseemshaik1993** [comment]
See I have checked the option enable authentication for Prometheus end point and tried accessing URL. Still the issue persists I can't be able to access the Jenkins Metrics. FYR below is the snip of the configuration and output:


<img width="807" alt="Screenshot 2024-06-06 120721" src="https://github.com/jenkinsci/prometheus-plugin/assets/96241675/393e543f-9fb9-4d33-86d2-d7810f5d412e">
<img width="805" alt="Screenshot 2024-06-06 121213" src="https://github.com/jenkinsci/prometheus-plugin/assets/96241675/47368d72-1c63-4849-a347-1138742c5cdf">

**Comment by waseemshaik1993** [comment]
Please guide me to get over this issue.

**Comment by Waschndolos** [comment]
@waseemshaik1993 try to remove the `/` in the Path configuration. It should be enough to simply have `prometheus` in there without the `/`

**Comment by waseemshaik1993** [comment]
@Waschndolos I have removed the `/` in the path configuration. Restarted the jenkins and again tried but the issue persists. What would be the next step, please do let me know.

**Comment by Waschndolos** [comment]
@waseemshaik1993. I would check the following:

* If you disable the authentication, does the plugin work in general? 
* Do you have any exception in the logs?
* In your Jenkins security config do you have authentication enabled at all?
* If yes, does the user have the permission Metrics.VIEW?

**Comment by waseemshaik1993** [comment]
@Waschndolos Please check the following:
      • If the authentication is disabled, still plugin is not working. I mean not able to see metrics while accessing http://jenkins-ip/8080/prometheus	
	• Can you please tell me which logs, these are the system logs checked in Jenkins:
	
<img width="463" alt="Screenshot 2024-06-07 110648" src="https://github.com/jenkinsci/prometheus-plugin/assets/96241675/0358edcb-6911-493b-9871-72d0c73e7c19">

	• Yes, tried checking first by enabling it and then by disabling as well. But no use.
	• Yes I created a new user 'prometheus' gave all the permissions to read/view metrics
	• Yes, matrix authorization strategy plugin installed and already gave permissions to user 'prometheus' metrics.view. Please check below snip
<img width="435" alt="Screenshot 2024-06-07 110207" src="https://github.com/jenkinsci/prometheus-plugin/assets/96241675/ebd63eae-d5c7-4918-b36b-c9d3b9cd732c">

**Comment by Waschndolos** [comment]
@waseemshaik1993. I just tested it with the latest version - works without an issue on my side. What I've seen is that when I didn't yet installed the prometheus plugin I had the same page as you. Maybe the update of the plugin failed somehow and is now in a strange state. You may go ahead and save a screenshot of your configuration of the prometheus plugin and then go ahead and uninstall and reinstall the plugin. Don't know what else could be the issue

**Comment by Waschndolos** [comment]
Is it still an issue?

**Comment by waseemshaik1993** [comment]
> Is it still an issue?

@Waschndolos Yes, the issue persists till now. I am not sure what exactly the issue is. I provided you all the details below.

Manage Jenkins Errors:
<img width="637" alt="Jenkins 0" src="https://github.com/jenkinsci/prometheus-plugin/assets/96241675/eeafe5a0-f3fa-48da-aeac-5ac7ca6a4111">

<img width="621" alt="Jenkins 1" src="https://github.com/jenkinsci/prometheus-plugin/assets/96241675/143dcc69-a7bd-4580-88b5-a5cf94a1d808">
<img width="617" alt="Jenkins 3" src="https://github.com/jenkinsci/prometheus-plugin/assets/96241675/becda3a2-9d8d-4196-875d-cc412c8ff9e3">
<img width="626" alt="Jenkins 4" src="https://github.com/jenkinsci/prometheus-plugin/assets/96241675/fa982d39-229d-41d6-a205-0aa485b11f4c">

Plugin-Updates required:
<img width="912" alt="Jenkins 5" src="https://github.com/jenkinsci/prometheus-plugin/assets/96241675/9474b1ac-60f5-4e27-9f49-253984b45090">

![image](https://github.com/jenkinsci/prometheus-plugin/assets/96241675/1e8c8eae-184c-48f6-8ced-585757008297

Installed Prometheus Plugins
<img width="896" alt="Jenkins 6" src="https://github.com/jenkinsci/prometheus-plugin/assets/96241675/c435132c-2573-4f22-ac2d-47a6873b5556">

**Comment by Waschndolos** [comment]
Have you deinstalled the plugin and reinstalled it?

**Comment by waseemshaik1993** [comment]
> Have you uninstalled the plugin and reinstalled it?

I did that, but i'll try reinstalling it again and let you know.

**Comment by waseemshaik1993** [comment]
Hi @Waschndolos I have tried reinstalling the prometheus plugin into jenkins. Please find below observations:
<img width="883" alt="image" src="https://github.com/jenkinsci/prometheus-plugin/assets/96241675/abc7f68d-6f9e-4e38-b00a-b62dcdadeeff">

**Comment by Waschndolos** [comment]
I guess you also restarted Jenkins afterwards. Puh.. no clue...
