### ISSUE TITLE
some of the metrics don't show up on prometheus end point

### ISSUE THREAD

**Issue by Trivikramreddy** [jenkinsci/prometheus-plugin#69]
I'm using the default setting for prometheus plugin in Jenkins and have them work through prometheus. The problem that I'm facing is I'm not able to see the default_jenkins_build metrics showing up in prometheus. I was able to see other metrics fine. I'm currently using this plugin on production and want to see  metrics about the last builds with the job name. I also see that when I'm trying to hit the https://jenkinsurl/prometheus it takes much longer time to load the metrics.

**Comment by kamrajshahapure** [comment]
> I'm using the default setting for prometheus plugin in Jenkins and have them work through prometheus. The problem that I'm facing is I'm not able to see the default_jenkins_build metrics showing up in prometheus. I was able to see other metrics fine. I'm currently using this plugin on production and want to see metrics about the last builds with the job name. I also see that when I'm trying to hit the https://jenkinsurl/prometheus it takes much longer time to load the metrics.

Did you manage to get a workaround, because I am also facing the exact issue
Not able to get default_* metrics to prometheus

**Comment by markyjackson-taulia** [comment]
I will look in to this tonight

**Comment by Trivikramreddy** [comment]
Thanks @markyjackson-taulia. Just want to let you know the current situation. Now i'm not even seeing the default_* metrics on the jenkins end point. I think this would help you out to get a workaround.

**Comment by markyjackson-taulia** [comment]
I couldn't reproduce this. Can you let me know how you have this configured and also the type of infra you have? Thanks

**Comment by Trivikramreddy** [comment]
As of now I'm able to see the metrics after enabling the authentication and using Basic auth. But is there any other way to do this more secure. I was able to see the metrics on prometheus end but when i try to see on the jenkins endpoint it shows 403 error even after i create the anonymous role with metrics view permission. Here is the snippet for that.
![screen shot 2018-10-08 at 9 59 26 am](https://user-images.githubusercontent.com/25829092/46620159-33c80900-cae1-11e8-8acf-252269653836.png)

**Comment by Taffarel** [comment]
@Trivikramreddy, I was having the same problem. The solution was to create a Jenkins user then configure a basic configuration at prometheus config xml

job_name: 'JenkinsMetrics'
  metrics_path: /prometheus
  basic_auth:
    username: prometheus
    password: "prometheus"
  static_configs:
    - targets:
      - 'jenkins-host:port'

**Comment by Trivikramreddy** [comment]
@Taffarel Thanks for your valuable response. We are currently using Role based Strategy So, i'm not able to create a separate user and assign the permission to view metrics. But what i did is created a token which has metrics view permission and used that in the basic auth. Is there any other way to do that more secure.

**Comment by markyjackson-taulia** [comment]
I can examine a different way to do this but that will take some time. For now can I close out this issue?

**Comment by Trivikramreddy** [comment]
@markyjackson-taulia Thanks !!! You can close the ticket.
