### ISSUE TITLE
default_jenkins_builds_unstable_build_count_total is missing unstable builds

### ISSUE THREAD

**Issue by avlitman** [jenkinsci/prometheus-plugin#695]
### Jenkins and plugins versions report

Hi all I'm using Grafana to visualize the jenkins Prometheus, and the `default_jenkins_builds_last_build_result_ordinal` is showing unstable or failed build and `default_jenkins_builds_unstable_build_count_total` does not show any growth.

### What Operating System are you using (both controller, and any agents involved in the problem)?

using fedora and jenkins UI

### Reproduction steps

myGrafana queries are:

sum (increase(default_jenkins_builds_unstable_build_count_total{jenkins_job=~".*$job_type.*", jenkins_job=~".*$version.*", jenkins_job=~"$job_name", jenkins_job!~".*$ignore_jobs.*"}[$__range]))

and:

(max by(jenkins_job) (default_jenkins_builds_last_build_result_ordinal{jenkins_job=~".*$job_type.*", jenkins_job=~".*$version.*", jenkins_job=~"$job_name", jenkins_job!~".*$ignore_jobs.*"}) !=-1 !=3 !=4)

I tried many more queries but it just miss builds from time to time, not for all jobs. and I'm not sure what to do I tried anything I found, seems like there is a bug with `default_jenkins_builds_*_build_count_total`.
*it's not a time issue since I checked that there is unstable builds that are not in the metric...

### Expected Results

All metrics show the same number of unstable builds, default_jenkins_builds_unstable_build_count_total should contain the same unstable builds as in default_jenkins_builds_last_build_result_ordinal.

### Actual Results

default_jenkins_builds_unstable_build_count_total not contain the same unstable builds as in default_jenkins_builds_last_build_result_ordinal, and the metric is not accurate for all the jobs.. it misses builds.

### Anything else?

Anyy help will be much appreciated! 

### Are you interested in contributing a fix?

With your guidelines and support- of course

**Comment by Waschndolos** [comment]
The metrics are calculated in rounds (specified by the plugin configuration). If you have parallel runs or runs of a job which run multiple times within that period it will only show the last build, therefore it can happen that you don't see all. Also if you configure to not include unstable builds it can happen. (writing from my memory - no code available right now)

**Comment by Waschndolos** [comment]
any comments?

**Comment by avlitman** [comment]
it's still strange that some metrics are reports some jobs and some not and in the UI you see all, I want to create a reliable dashboard to monitor my CI process this is why I'm asking.

sorry for the delay somehow I missed your replay and thanks a lot!

**Comment by avlitman** [comment]
> any comments?

first thanks a lot for your time!

second, my issue is that I want to create a reliable dashboard to monitor my CI jobs, and it's important for us to see if there is 100% failures. at the current stat the `default_jenkins_builds_*_build_count_total` metrics miss from time to time a specific job run which leads to 100% failure even if there was an unstable/successful job, and there is a big difference if the failure rate is 97% instead of 100%.. hope I make sense.

Let me share with you a few screenshot as an example:
![Screensh
![Screenshot from 2024-09-24 14-58-09](https://github.com/user-attachments/assets/569bd695-967b-4f6b-9fc1-48992f543374)
ot from 2024-09-24 14-30-21](https://github.com/user-attachments/assets/c494093f-3626-41c3-b112-088cb6b9e1ef)
![Screenshot from 2024-09-24 14-59-13](https://github.com/user-attachments/assets/b052fd1c-40a2-4d1d-a031-d668d4a4b671)

so as you can see it didn't catch the one unstable build.. and I'm not sure why

**Comment by Waschndolos** [comment]
Which value do you have configured in "Collecting metrics period in seconds"?

**Comment by avlitman** [comment]
@Waschndolos what do you mean by "Collecting metrics period in seconds"? which metric?

**Comment by avlitman** [comment]
> Which value do you have configured in "Collecting metrics period in seconds"?

do you know maybe how can I check that?

**Comment by Waschndolos** [comment]
In the Jenkins configuration page in the saction of the plugin there's an input field where you can set it

**Comment by Waschndolos** [comment]
![image](https://github.com/user-attachments/assets/d4d61087-76c8-46a4-ae61-a82a23bb2e89)

**Comment by Waschndolos** [comment]
Close due to inactivity
