### ISSUE TITLE
Metrics to show failed stages names of pipelines

### ISSUE THREAD

**Issue by ravindrakmr** [jenkinsci/prometheus-plugin#696]
### What feature do you want to see added?

Request to add a metric to show names of failed stages over a period of time.

**Comment by Waschndolos** [comment]
What could be done is something like that:

`default_jenkins_builds_last_stage_result_ordinal{jenkins_job="MyPipeline",repo="NA",buildable="true",stage="stage skipped",} 0.0
default_jenkins_builds_last_stage_result_ordinal{jenkins_job="MyPipeline",repo="NA",buildable="true",stage="stage not ok",} 5.0
default_jenkins_builds_last_stage_result_ordinal{jenkins_job="MyPipeline",repo="NA",buildable="true",stage="stage final",} 5.0
default_jenkins_builds_last_stage_result_ordinal{jenkins_job="MyPipeline",repo="NA",buildable="true",stage="stage ok",} 2.0`

Would that be enough?

**Comment by yury-tyumin** [comment]
It seems like a helpful enhancement.

@Waschndolos in your example, there is a status with a value of 5.0. What does this mean? 
According to the documentation, the result_ordinal metric only includes statuses from 0 to 4
`(0=SUCCESS, 1=UNSTABLE, 2=FAILURE, 3=NOT_BUILT, 4=ABORTED)`

**Comment by Waschndolos** [comment]
good question... I'll check once I come back home

**Comment by ravindrakmr** [comment]
> What could be done is something like that:
> 
> `default_jenkins_builds_last_stage_result_ordinal{jenkins_job="MyPipeline",repo="NA",buildable="true",stage="stage skipped",} 0.0 default_jenkins_builds_last_stage_result_ordinal{jenkins_job="MyPipeline",repo="NA",buildable="true",stage="stage not ok",} 5.0 default_jenkins_builds_last_stage_result_ordinal{jenkins_job="MyPipeline",repo="NA",buildable="true",stage="stage final",} 5.0 default_jenkins_builds_last_stage_result_ordinal{jenkins_job="MyPipeline",repo="NA",buildable="true",stage="stage ok",} 2.0`
> 
> Would that be enough?

Yes that will be helpful. Thanks for considering it @Waschndolos . Let's see what status 5.0 says.

**Comment by Waschndolos** [comment]
![grafik](https://github.com/user-attachments/assets/bd6231e3-e48c-47db-a776-10f29edb6f6a)

Where i get the information from is com.cloudbees.workflow.rest.external.StatusExt in that case it's "FAILED".. but that differs from the "official" Result of a Job 
![grafik](https://github.com/user-attachments/assets/07680126-89ad-4613-af20-de639b040816)

I guess a mapping to the "offical" Result class need to be done right? What do you think?

**Comment by ravindrakmr** [comment]
Yes I think mapping to official result makes sense to me.

**Comment by Waschndolos** [comment]
Hm.. Currently working on it and while I was working I think maybe it's not good to have a mapping. The StatusExt has additional useful information like "IN_PROGRESS" and "PAUSED_PENDING_INPUT" which are also things one could track so I'll stay with the oritinal Ordinals of StatusExt and document the ordinals

**Comment by Waschndolos** [comment]
@ravindrakmr could you check the PR if it fits your needs?

**Comment by ravindrakmr** [comment]
Hi @Waschndolos. PR looks good.

**Comment by Waschndolos** [comment]
Ok cool thank you for checking. I found one strange issue when I run it with hpi:run. I'll do a check if that's concerning and prepare a release once it's done.
