### ISSUE TITLE
Add the ability to exclude metrics based on label values

### ISSUE THREAD

**Issue by shanilempel** [jenkinsci/prometheus-plugin#698]
### What feature do you want to see added?

Currently, this plugin allows metrics to be excluded by their names. I would like to request the ability to exclude metrics based on the value of specific labels, particularly the `jenkins_job` label. This would allow users to filter and expose only a subset of metrics based on label values, rather than excluding entire metric types.

This is particularly useful when managing environments with numerous jobs, as it would allow users to reduce the volume of metrics exposed by excluding irrelevant or less critical jobs. 🙏

**Comment by Waschndolos** [comment]
Also filtered by regex?

**Comment by shanilempel** [comment]
I can manage with exact names, but regex would be even better.

**Comment by Waschndolos** [comment]
Ok. Maybe I have some time later today. I will check.

**Comment by PayBas** [comment]
While the functionality is a welcome new feature, wouldn't it have been way more user-friendly to simply add a checkbox option to all jobs which determines whether the job is included in the metrics or not?

If you have a large Jenkins with 100+ jobs and you want to exclude 30 of them, having a single regex that needs to filter them all exactly might be practically impossible to do.

**Comment by Waschndolos** [comment]
You're not limited to one Regex: 
![image](https://github.com/user-attachments/assets/0baa121a-06bb-402d-b768-42c139eb7193)

I also host a Jenkins instance with ~3000 jobs. Having checkboxes would not be comfortable to configure. Usually you have some naming convention on that size so regex is the most comfortable for admins.

**Comment by PayBas** [comment]
Fair enough. Thanks for clarifying :)
