### ISSUE TITLE
default_jenkins_builds_duration_milliseconds_summary_count returns incorrect values

### ISSUE THREAD

**Issue by stefanboicu** [jenkinsci/prometheus-plugin#70]
Querying Prometheus for the default_jenkins_builds_duration_milliseconds_summary_count of a certain job over one hour (or more) returns a random value at certain scrapes:

{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"__name__":"default_jenkins_builds_duration_milliseconds_summary_count","instance":"ia00049vm:8080","jenkins_job":"CollectorJenkins","job":"jenkins"},"values":[[1539168359.137,"2050"],[1539168419.137,"2050"],[1539168479.137,"2050"],[1539168539.137,"2050"],[1539168599.137,"2050"],[1539168659.137,"2050"],**[1539168779.137,"4100"]**,[1539168839.137,"2050"],[1539168899.137,"2050"],[1539168959.137,"2050"],[1539169019.137,"2050"],[1539169079.137,"2050"],[1539169139.137,"2050"],[1539169199.137,"2050"],[1539169259.137,"2050"],[1539169319.137,"2050"],[1539169379.137,"2050"],[1539169439.137,"2050"],[1539169499.137,"2050"],[1539169559.137,"2050"],[1539169619.137,"2050"],[1539169679.137,"2050"],[1539169739.137,"2050"],[1539169799.137,"2050"],[1539169859.137,"2050"],[1539169919.137,"2050"],[1539169979.137,"2050"],[1539170039.137,"2050"],[1539170099.137,"2050"],[1539170159.137,"2050"],[1539170219.137,"2050"],[1539170279.137,"2050"],[1539170339.137,"2050"],[1539170399.137,"2050"],[1539170459.137,"2051"],[1539170519.137,"2051"],[1539170579.137,"2051"],[1539170639.137,"2051"],[1539170699.137,"2051"],[1539170759.137,"2051"],[1539170819.137,"2051"],[1539170879.137,"2051"],[1539170939.137,"2051"],[1539170999.137,"2051"],[1539171059.137,"2051"],[1539171119.137,"2051"],[1539171179.137,"2051"],[1539171239.137,"2051"],[1539171299.137,"2051"],[1539171359.137,"2051"],[1539171419.137,"2051"],[1539171479.137,"2051"],[1539171539.137,"2051"],[1539171599.137,"2051"],[1539171659.137,"2051"],[1539171719.137,"2051"],[1539171779.137,"2051"],[1539171839.137,"2051"]]}]}}

The value is usually twice the value of the correct count but it's not always the case. I am using Jenkins 2.107.3 with Promtheus Plugin v2.0 and a scrape interval of 60s

**Comment by markyjackson-taulia** [comment]
Good catch. I will look in to this
