### ISSUE TITLE
Number of outdated plugins

### ISSUE THREAD

**Issue by jader31** [jenkinsci/prometheus-plugin#701]
### What feature do you want to see added?

I'd like to see how many plugins need to be updated.
I love keep my install up to date, but maybe I can generate an alert once 2 or more plugins are needing to be updated and avoid to update jenkins just for one plugin.

### Are you interested in contributing this feature?

sorry, just a sysadmin, no programming skills. But I can test it once is done before to be published (GA).

**Comment by Waschndolos** [comment]
There is a metric called `jenkins_plugins_withUpdate`

**Comment by jader31** [comment]
Hi Waschndolos

I got that metric, but I thought it would show only 1 (there are updates) /
0 (no updates ).
It counts how many plugins needs to be updated ? If so, I suggest you to
update description to tell that info.

*# HELP jenkins_plugins_withUpdate *HOW MANY PLUGINS NEED TO BE UPDATED

      (could remove this: Generated from Dropwizard metric import
(metric=jenkins.plugins.withUpdate,

      type=jenkins.metrics.impl.JenkinsMetricProviderImpl$23*)*

      *Jm: this info appears to be autogenerated and show conflicting
info about type and AFAIK useless info for most of users
      Yes, I am a PAIN IN THE ASS... for sure. If you need help to
update ALL lines, I can help... it's just HARD WORK and I can learn in
the process! *

*      Right now I'm not employed (since Sept 8th when I was laid off!!)     *

*
# TYPE jenkins_plugins_withUpdate gauge*

I'll wait for plugins updates and validate it show ok! Thank you!

Jáder Marasca

+55.83.999.899.232 (Tim WhatsApp)
+55.51.2160.8383 (VoIP)



Em qua., 25 de set. de 2024 às 11:04, Waschndolos ***@***.***>
escreveu:

**Comment by Waschndolos** [comment]
Actually the metric comes from this plugin: https://github.com/jenkinsci/metrics-plugin (so if there's anything wrong with it you may open an issue there) 

The description is:

> jenkins.plugins.withUpdate (gauge)
> 
> The number of plugins in the Jenkins instance that have an newer version reported as available in the current Jenkins update center metadata held by Jenkins. This value is not indicative of an issue with Jenkins but high values can be used as a trigger to review the plugins with updates with a view to seeing whether those updates potentially contain fixes for issues that could be affecting your Jenkins instance.

In case of my jenkins instance it shows:

```
# HELP jenkins_plugins_withUpdate Generated from Dropwizard metric import (metric=jenkins.plugins.withUpdate, type=jenkins.metrics.impl.JenkinsMetricProviderImpl$23)
# TYPE jenkins_plugins_withUpdate gauge
jenkins_plugins_withUpdate 40.0
```

So it appears to already do the thing you're want it to do?

**Comment by jader31** [comment]
Hi,

Yes, it show the number of plugins requiring updates! Thank you!

Jáder Marasca
+55.83.999.899.232 (Tim WhatsApp)
+55.51.2160.8383 (VoIP)



Em qui., 26 de set. de 2024 às 06:31, Waschndolos ***@***.***>
escreveu:
