### ISSUE TITLE
Uninstalling & Installing Jenkins Prometheus Metrics Plugin

### ISSUE THREAD

**Issue by LeylaSkk** [jenkinsci/prometheus-plugin#712]
I am experiencing issues with the Jenkins Prometheus metrics plugin. Specifically, I have attempted to uninstall the plugin and reinstall it multiple times, but the installation process consistently gets stuck at the initialization stage. 

When I try to access the Prometheus metrics for Jenkins, I cannot find any relevant configuration. Additionally, refreshing the page during the installation appears to show that the plugin has been downloaded, but it does not function as expected.

Steps to reproduce the issue:
1. Navigate to the Jenkins plugin manager.
2. Uninstall the Jenkins Prometheus metrics plugin.
3. Attempt to reinstall the plugin.
4. Observe that the installation process gets stuck during initialization.

**Expected behavior:**  
The plugin should install successfully and be accessible in the Prometheus metrics.

**Actual behavior:**  
The plugin fails to install properly, and refreshing the page during installation causes confusion regarding its status.

Any assistance or guidance on resolving this issue would be greatly appreciated.

Thank you!

**Comment by Waschndolos** [comment]
Just tried the reproduction steps. Had no issues at all. Do you have any logs of the installation process?

**Comment by LeylaSkk** [comment]
Thank you for testing the reproduction steps!

To provide some context, I am running Jenkins on Vagrant. The issue I’m
encountering is that the "uninstalling pending" status for the Prometheus
metrics plugin only clears after I perform a safe restart of Jenkins.

After restarting Jenkins, when I attempt to download the plugin again, it
consistently gets stuck in the initializing phase. Unfortunately, I don’t
have logs of the installation process at the moment, but I can gather them
if needed.

Let me know if you have any further questions or if there’s a specific log
file I should look into for troubleshooting. I appreciate your help!

Le mar. 29 oct. 2024 à 12:45, Waschndolos ***@***.***> a
écrit :

**Comment by Waschndolos** [comment]
Never heard of such issues to be honest. Usually you uninstall a plugin, perform a restart and then Jenkins does not have any reference to the plugin anymore. Can it be that you us the jenkins as code plugin and that this comes in to play here?

**Comment by Waschndolos** [comment]
Any updates on this?
