### ISSUE TITLE
PROMETHEUS_ENDPOINT not use when change

### ISSUE THREAD

**Issue by mandracke1976** [jenkinsci/prometheus-plugin#73]
Hello,

The default value is correctly use, but when I change the value by 'metrics' by example, the page is ot found.

Do we have to restart the master to take account the change. I haven't found the information.

**Comment by markyjackson-taulia** [comment]
You should not have to restart the master. What version are you using for Jenkins?

**Comment by markyjackson-taulia** [comment]
🤔 Let me see if I can recreate this using that version

**Comment by mrmaus** [comment]
Had the same issue, looks like the specific value 'metrics' conflicts with url mapping in metrics plugin (check MetricsRootAction#getUrlName). Setting it to metrics2 or any other value works
