### ISSUE TITLE
Feature request: Add status for the last completed build

### ISSUE THREAD

**Issue by jamesrobson-pio** [jenkinsci/prometheus-plugin#74]
The exporter currently shows the status of the last build, it would be useful to have the status of the last completed build as well. We want to include this in a grafana dashboard and having the status change to 'building' is not ideal.

**Comment by markyjackson-taulia** [comment]
I am preparing for a December release and will do my best to fit this in to that release @jamesrobson-pio

**Comment by stujb** [comment]
Is it possible to have a last completed build duration added as well as last completed build status ? Currently when a build is in flight the last build duration metric goes to 0 until the build is completed.
