### ISSUE TITLE
Feature Request: Node Load

### ISSUE THREAD

**Issue by chrisaaaaa** [jenkinsci/prometheus-plugin#77]
I would like to graph how many jobs are running on a node over time, there are metrics for total builds on a node but not the current state.

The stats could look like this;
  jenkins_node_nodename_build_executors 2.0
  jenkins_node_nodename_builds_current 1.0

In this case I could say the node is 50% loaded at that point in time.

**Comment by darxriggs** [comment]
A node should be provided as metric label, not as part of the metric name.

**Comment by Zauxst** [comment]
> A node should be provided as metric label, not as part of the metric name. See https://prometheus.io/docs/concepts/data_model/

That's true, but the feature would still be nice to have. Especially if coupled with a plugin like the Kubernetes Slaves Plugin.

It would still be particularly helpfull to get metrics per node.
Instead of the proposed metrics you could've use:
```
jenkins_node_load_average{agent-name="HOSTNAME"} 10
etc.
```
