### ISSUE TITLE
Document unit of duration metrics

### ISSUE THREAD

**Issue by fho** [jenkinsci/prometheus-plugin#80]
https://wiki.jenkins.io/display/JENKINS/Metrics+Plugin

It's not clear from the documentation in which unit the duration metrics are.
Is it seconds? Milliseconds?

It would be great to document the unit or even better add the unit as part of the metric name

**Comment by markyjackson-taulia** [comment]
The one part that has been lacking since I took over this project is the documentation. I will make a plan to add more the 1st or 2nd week of Jan..
I am adding this as a feature request

**Comment by darxriggs** [comment]
I suggest to stick to the best practices and have to unit be part of the metric name - see https://prometheus.io/docs/practices/naming/.

**Comment by okor** [comment]
Well. So what is the unit?
