### ISSUE TITLE
Expose per-Job durations and results

### ISSUE THREAD

**Issue by fho** [jenkinsci/prometheus-plugin#81]
We would like to record and visualize the runtime and result for specific Jenkins jobs.
It would be great if the plugin would expose a metric that contains the job_runtime and has labels for the jobname and result

**Comment by daganibhanu** [comment]
is this feature available now?

**Comment by daganibhanu** [comment]
@markyjackson-taulia any update on this?

**Comment by markyjackson-taulia** [comment]
This is not available yet. Debugging some new issues with java 11 testing. Should have a new release by end of this week

**Comment by daganibhanu** [comment]
@markyjackson-taulia Thanks for the update

**Comment by MatteoMori** [comment]
Hey guys, 
do you have any updates on this? It does seems like a very cool feature to have :-)
kind regards,
Matteo

**Comment by darxriggs** [comment]
A clear understanding of `metrics` vs. `events` is required to decide if and how to implement this. The [What Is the Difference Between Metrics and Events?](https://dzone.com/articles/what-is-the-difference-between-metrics-and-events) might be a starting point.

Prometheus is about `metrics`, not `events`. There is also a [FAQ entry](https://prometheus.io/docs/introduction/faq/#how-to-feed-logs-into-prometheus) dedicated to this. Job builds are `events`.

Quick Example
- The prometheus scrape interval is 10 seconds.
- Within such a period 5 builds have been run on Jenkins.
- The builds originate from 3 jobs and have 2 different results (SUCCESS, FAILURE).

The question therefore is, which `metrics` to provide for these `events` and if this is useful and feasible at all. It could be a [summary](https://prometheus.io/docs/concepts/metric_types/#summary) for durations (job name and result as label) which also provides a result count. A possible cardinality explosion (number of jobs x number of results) should also be kept in mind - see [Metric and label naming](https://prometheus.io/docs/practices/naming/).

**Comment by fho** [comment]
@MatteoMori
I wrote an exporter for Jenkins build metrics https://github.com/simplesurance/jenkins-exporter. 
It can be used as temporary solution until the plugin exports the metrics.

**Comment by ssrivastava-papajohns** [comment]
@markyjackson-taulia is this feature done?
