### ISSUE TITLE
Support for Folders

### ISSUE THREAD

**Issue by jwhitcraft** [jenkinsci/prometheus-plugin#9]
If a job is in a folder, it would be nice to get the folder name as attribute so it's easier to group similar jobs.

**Comment by lsjostro** [comment]
Indeed! 👍  PR welcome! :)

**Comment by chenfli** [comment]
Look at my PR https://github.com/jenkinsci/prometheus-plugin/pull/66

**Comment by markyjackson-taulia** [comment]
Closing this put as pr #66 was merged
