### ISSUE TITLE
Putting new releases on hold for a week due

### ISSUE THREAD

**Issue by markyjackson-taulia** [jenkinsci/prometheus-plugin#92]
Hey all,
I found a few new bugs which will come in to an upcoming security release. 
I also spent the last week during the presentation circuit.
The new release will drop this week (to also include the lost binary due to an artifactory blurb).
I just got home from a Stanford talk about prometheus and I really thank you all for driving that as well as supporting this. 
A lot of exciting news coming in the next few days so standby and I appreciate the patients.
Also did everyone hear about the CDF changes coming?

**Comment by icereed** [comment]
Thanks for the update! Waiting excitedly for the next release.

**Comment by hsatterwhite-transloc** [comment]
@markyjackson-taulia, is this issue still relevant? I'm new to the plugin as of a couple of days ago and was wondering where or not if the impending release in this issue has cut or not?

**Comment by markyjackson-taulia** [comment]
@hsatterwhite-transloc You should be good, I forgot to close this

**Comment by hsatterwhite-transloc** [comment]
@markyjackson-taulia What does "You should be good, I forgot to close this" mean?

Are you cutting a release? The latest release in GitHub is was on 08/30/2018 and this issue was opened on 02/07/2019.

**Comment by markyjackson-taulia** [comment]
Let me take a look at that

**Comment by markyjackson-taulia** [comment]
I am working hard to get a new release out. I am also looking for co-maintainers to help with the load as I am the only one

**Comment by hsatterwhite-transloc** [comment]
@markyjackson-taulia Thanks for the quick response. By chance do you have a rough estimate on when the next release will be cut and what the changes may be?

**Comment by markyjackson-taulia** [comment]
I will work hard to get it in at some point by end of day Sunday.
