### ISSUE TITLE
Create metrics from shared pipeline

### ISSUE THREAD

**Issue by InTheCloudDan** [jenkinsci/prometheus-plugin#94]
I'd be really nice if we could add in metrics from various stages and functions in our Jenkins pipeline to be able to start getting observability into them.

**Comment by markyjackson-taulia** [comment]
Thanks for submitting this @InTheCloudDan I am trying to get another release out this month (I have really slipped) and I will try to get this in, if not this coming release the next for sure

**Comment by markyjackson-taulia** [comment]
In the new version

**Comment by kstrijbos** [comment]
@markyjackson-taulia Do you have an update? We'd also like to publish custom metrics from our shared library to the prometheus endpoint.

**Comment by kstrijbos** [comment]
@markyjackson-taulia We could also implement this if wanted? I could add a thread-safe CollectorRegistry wrapper which offers a registerOrGet() method?

**Comment by ipmsteven** [comment]
Hi @markyjackson-taulia , could you share more details about this change? Thanks!
