### ISSUE TITLE
Build number filter

### ISSUE THREAD

**Issue by jodybro** [jenkinsci/prometheus-plugin#95]
Version: `2.0.0` from the marketplace

According to this: https://github.com/jenkinsci/prometheus-plugin/issues/31
The build number should be an exported label.

But when I look at metrics like `default_jenkins_builds_last_build_result_ordinal` the only label I see on them is the `job_attribute_name`.

Is the label not available anymore?

**Comment by jodybro** [comment]
Clicked close by mistake

**Comment by aditya-konarde** [comment]
-1 to exposing it as a label; If you're looking at hundreds or even thousands of builds, this is definitely likely to cause a cardinality explosion. Please see: https://prometheus.io/docs/practices/naming/#labels

```
CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.
```
